enhavo/enhavo

src/Enhavo/Bundle/AppBundle/Resources/public/css/theme.css

As per issue #90 "Too much spacing to button bar"
Changes bottom padding on modals for content creation and user creation to 50px, which matches the padding set on the top.

update tabs bottom padding to match the top padding

---

src/Enhavo/Bundle/GeneratorBundle/Generator/GridItemGenerator.php

Grid item generator: changed table name and form type alias in generated files to not include the postfix 'bundle' from bundle name

Removed "bundle" from table name and form type alias

---

src/Enhavo/Bundle/GeneratorBundle/Command/GenerateGridItemCommand.php
src/Enhavo/Bundle/GeneratorBundle/Generator/GridItemGenerator.php

Changed command name from "enhavo:generate:grid:item" to "enhavo:generate:grid-item"
Removed "grid_item" from default database table name and form type alias

Grid Item Generator: changed names

---

src/Enhavo/Bundle/MediaBundle/Controller/FileController.php

Apache adds a (wrong) value to max-age header if expires header is not set

add expires header to format action

---

src/Enhavo/Bundle/MediaBundle/Media/PublicUrlGenerator.php

avoid exception on page (media_url) when original file is missing before thumbnail was generated

avoid exception on page (media_url) when original file is missing

---

src/Enhavo/Bundle/NavigationBundle/Form/Type/NodeCollectionType.php

The model class on `NavItemType` can be `null` for valid reasons. E.g. empty nav item as placeholder. This PR allowed to set model as `null`

Fix empty navigation model

---

assets/node_modules/@enhavo/vue-form/form/FormFactory.ts
assets/node_modules/@enhavo/vue-form/tests/form/FormFactory.mocha.ts
assets/node_modules/@enhavo/vue-form/tests/mock/TestFactory.ts
assets/node_modules/@enhavo/vue-form/tests/mock/TestForm.ts
package.json
test/tsconfig.test.json
tsconfig.test.json

Use `ts-node` to transpile mocha tests written in typescript. `TS_NODE_SKIP_IGNORE` must be `true` in order to use tests inside `node_modules`

Add typescript support for mocha tests

---

src/Enhavo/Bundle/AppBundle/Filter/Type/BooleanType.php
src/Enhavo/Bundle/AppBundle/Filter/Type/OptionType.php
src/Enhavo/Bundle/AppBundle/Filter/Type/TextType.php
src/Enhavo/Bundle/MultiTenancyBundle/Filter/TenancyFilterType.php

Some filter types (Boolean, Option and Tenancy) still didn't support dot notation on the property parameter to create join queries. I updated all of these, and also simplified the code in TextType to match the other filters.

[AppBundle/MultiTenancyBundle] Updated all filters to allow dot property path notation

---

src/Enhavo/Bundle/AppBundle/Filter/FilterQuery.php
src/Enhavo/Bundle/AppBundle/Filter/FilterQueryOr.php

Expanded FilterQuery to allow adding OR blocks.
`$filterQuery->or()->addWhere('property1', '=', 'value1')->addWhere('property2', '=', 'value2');`
These blocks will be added as an AND statement in parenthesis, like this:
`AND (property1 = "value1" OR property2 = "value2")`

[AppBundle] Added possibility to add OR blocks to FilterQuery

---

assets/node_modules/@enhavo/form/assets/styles/module/_icheck.scss
assets/node_modules/@enhavo/form/type/CheckboxType.ts

FormBundle's BooleanType previously ignored the html attribute "readonly". The "disabled" attribute worked, but had no accompanying style. This PR adds both the readonly functionality and styles for both readonly and disabled.

[FormBundle] BooleanType readonly/disabled

---

src/Enhavo/Bundle/TranslationBundle/Form/EventListener/ReplaceTranslationTypeListener.php

For `PolyCollectionType` forms, the `TranslationType` was applied twice. Somehow, the behaviour changed here, but couldn't find out why. This bugfix prevent applying the `TranslationType` a second time

Fix reapply translation type

---

.github/mergify.yml
.github/workflows/subtree.yml

Use also `0.9` branch for subtree split and `0.10` for backports

Use 0.9 branch for subtree split and 0.10 for backport

---

.github/workflows/release.yml

| Backport      | 0.9,0.10
Fix required github user to push tags to subtrees

Fix git user for release

---

assets/node_modules/@enhavo/form/loader/PolyCollectionLoader.ts
assets/node_modules/@enhavo/form/services/loader.yaml
assets/node_modules/@enhavo/form/type/PolyCollectionConfig.ts
assets/node_modules/@enhavo/form/type/PolyCollectionItem.ts
assets/node_modules/@enhavo/form/type/PolyCollectionType.ts
src/Enhavo/Bundle/AppBundle/Resources/translations/javascript.de.yml
src/Enhavo/Bundle/AppBundle/Resources/translations/javascript.en.yml
src/Enhavo/Bundle/FormBundle/Form/Type/PolyCollectionType.php

Add `confirm_delete` option to `PolyCollectionType` to better protected items if needed

Add confirm delete option to PolyCollectionType

---

.github/workflows/subtree.yml

Add `enhavo-bot` as git user to subtree split in case if needed for e.g. force pushes

Add git user to subtree workflow

---

src/Enhavo/Bundle/TranslationBundle/Form/Extension/TranslationExtension.php

The function `getExtendedTypes` should be static.

Fix translation extension

---

src/Enhavo/Bundle/FormBundle/Formatter/CurrencyFormatter.php
src/Enhavo/Bundle/FormBundle/Tests/Formatter/CurrencyFormatterTest.php

fix CurrencyFormatter->getInt + Test

---

assets/node_modules/@enhavo/app/action/model/FilterAction.ts
assets/node_modules/@enhavo/app/grid/filter/components/FilterBetweenComponent.vue
assets/node_modules/@enhavo/app/grid/filter/components/FilterDateBetweenComponent.vue
assets/node_modules/@enhavo/app/grid/filter/model/BetweenFilter.ts
src/Enhavo/Bundle/AppBundle/Filter/Type/BetweenFilterType.php

As part of the recent filters rework, the labels of filters are now displayed in a dropdown menu. But the BetweenFilterType stored its labels as an object instead of a string, which lead to filters of this type displaying a stringified json as label. This should fix this issue.

[AppBundle] Fixed label of filters type BetweenFilterType displayed as json

---

assets/node_modules/@enhavo/app/assets/styles/components/_menu.scss
src/Enhavo/Bundle/AppBundle/Menu/Menu/BaseMenu.php

When you right click on an enhavo menu item and open it in a new browser tab, the resulting page would have a view without a valid id, which could then lead to javascript errors and infinite loading overlays on subsequent calls. This bugfix fixes that issue.
It also fixed a style error if a menu items a-element has the :visited state.

[AppBundle] Fixed bug when opening a menu link in a new browser tab

---

assets/node_modules/@enhavo/app/encore/AppTestPackage.js
assets/node_modules/@enhavo/vue-form/data/FormData.ts
assets/node_modules/@enhavo/vue-form/form/Form.ts
assets/node_modules/@enhavo/vue-form/form/Theme.ts
assets/node_modules/@enhavo/vue-form/index.ts
assets/node_modules/@enhavo/vue-form/tests/form/FormTest.mocha.ts
assets/node_modules/@enhavo/vue-form/tests/form/ThemeTest.mocha.ts
karma.conf.js
package.json
src/Enhavo/Bundle/VueFormBundle/EnhavoVueFormBundle.php

You can pass now a `Theme` object to `Form` to change components and properties

Add theming to forms

---

assets/node_modules/@enhavo/vue-form/components/FormHiddenComponent.vue

Fix hidden vue form type. With no name the the form field won't be send

Fix hidden vue form type

---

assets/node_modules/@enhavo/app/assets/styles/components/_menu.scss

If menu links had the :visited state, the color change on :hover no longer worked. This PR fixes this error.

[AppBundle]Fixed menu hover style not working on menu link with :visited state

---

src/Enhavo/Bundle/AppBundle/Filter/FilterQuery.php

Fixed entries in list views disappearing based on orderby due to innerjoin being used in FilterQuery.

[AppBundle] Fixed entries in list views disappearing based on orderby

---

assets/node_modules/@enhavo/app/assets/styles/view.scss

Added responsive styles for dropdown actions below 768px screen with. The dropdown menu items were quite small on mobile screens.

Added responsive styles for dropdown actions

---

src/Enhavo/Bundle/SettingBundle/Setting/AbstractSettingType.php
src/Enhavo/Bundle/SettingBundle/Setting/Setting.php
src/Enhavo/Bundle/SettingBundle/Setting/SettingTypeInterface.php
src/Enhavo/Bundle/SettingBundle/Setting/Type/BaseSettingType.php
src/Enhavo/Bundle/SettingBundle/Setting/Type/BooleanSettingType.php
src/Enhavo/Bundle/SettingBundle/Setting/Type/CurrencySettingType.php
src/Enhavo/Bundle/SettingBundle/Setting/Type/DateTimeSettingType.php
src/Enhavo/Bundle/SettingBundle/Setting/Type/EntitySettingType.php
src/Enhavo/Bundle/SettingBundle/Setting/Type/FloatSettingType.php
src/Enhavo/Bundle/SettingBundle/Setting/Type/IntegerSettingType.php
src/Enhavo/Bundle/SettingBundle/Setting/Type/MediaSettingType.php
src/Enhavo/Bundle/SettingBundle/Setting/Type/ParameterSettingType.php
src/Enhavo/Bundle/SettingBundle/Setting/Type/StringSettingType.php
src/Enhavo/Bundle/SettingBundle/Setting/Type/TextSettingType.php
src/Enhavo/Bundle/SettingBundle/Setting/Type/ValueAccessSettingType.php
src/Enhavo/Bundle/SettingBundle/Tests/Setting/SettingManagerTest.php
src/Enhavo/Component/Type/AbstractContainerType.php
src/Enhavo/Component/Type/AbstractType.php
src/Enhavo/Component/Type/TypeInterface.php

The `key` in a type shouldn't be a property, because the type exists only once, while a container holding a type can exists more often with different keys, so we are not able to provide a key inside a type.

Remove key from concrete type

---

src/Enhavo/Bundle/MediaBundle/Twig/MediaExtension.php

Twig function like `media_parameter` should accept `null` as file and return empty string like `media_url` does. This helps to keep the twig code more clean, instead of adding `if` cases all the time

Fix media twig function accept null

---

src/Enhavo/Bundle/ContentBundle/Resources/translations/EnhavoContentBundle.de.yaml
src/Enhavo/Bundle/ContentBundle/Resources/translations/EnhavoContentBundle.en.yaml

There was a missing translation for form.label.canonical_url in ContentBundle. Added one.

[ContentBundle] Added missing translation

---

src/Enhavo/Bundle/DoctrineExtensionBundle/Tests/EventListener/ReferenceSubscriberTest.php
src/Enhavo/Bundle/TranslationBundle/Form/EventListener/ReplaceTranslationTypeListener.php
src/Enhavo/Bundle/TranslationBundle/Tests/Form/Type/TranslationTypeTest.php

After saving translation for block entities, the references of the form was not the same as the translation reference, this leads to duplicate block entities and messed up translations.

Fix wrong translation reference

---

src/Enhavo/Bundle/TranslationBundle/EventListener/DoctrineTranslationSubscriber.php

fix Proxy being translated after not beeing detached during flush

---

src/Enhavo/Bundle/MediaBundle/Command/RefreshFormatCommand.php
src/Enhavo/Bundle/MediaBundle/Controller/FileController.php
src/Enhavo/Bundle/MediaBundle/Filter/Filter/BackgroundFilter.php
src/Enhavo/Bundle/MediaBundle/Filter/Filter/ImageBlurFilter.php
src/Enhavo/Bundle/MediaBundle/Filter/Filter/ImageFilter.php
src/Enhavo/Bundle/MediaBundle/Filter/Filter/ImageZoomFilter.php
src/Enhavo/Bundle/MediaBundle/Media/FormatManager.php

Fix deadlock, which occurred when creating a format and an error was thrown. Also improve error message and avoid create empty files on error.

Fix media deadlock and improve error output

---

src/Enhavo/Bundle/NewsletterBundle/EnhavoNewsletterBundle.php
src/Enhavo/Bundle/NewsletterBundle/Resources/config/services/services.yaml

put context to namespaces to avoid overlapping

---

src/Enhavo/Bundle/NewsletterBundle/EventListener/NewsletterSubscriber.php
src/Enhavo/Bundle/NewsletterBundle/Model/NewsletterInterface.php
src/Enhavo/Bundle/NewsletterBundle/Newsletter/NewsletterManager.php
src/Enhavo/Bundle/NewsletterBundle/Resources/config/services/services.yaml
src/Enhavo/Bundle/NewsletterBundle/Tests/Storage/LocalTypeStorageTest.php

Set `createdAt` date if newsletter was created

Fix newsletter created at

---

src/Enhavo/Bundle/BlockBundle/Resources/config/doctrine/Node.orm.xml
src/Enhavo/Bundle/DoctrineExtensionBundle/EventListener/ReferenceChange.php
src/Enhavo/Bundle/DoctrineExtensionBundle/EventListener/ReferenceSubscriber.php

When deleting and add a block node in the same request, the `ReferenceListener` call the flush multiple times. That leads to a doctrine dirty entity exception. The `postFlush` is triggered before doctrine cleanup all his temporarily metadata. I guess this a problem, so now we track the changes and execute them separate without a doctrine flush routine.

Fix delete and create node

---

src/Enhavo/Bundle/DoctrineExtensionBundle/EventListener/ReferenceSubscriber.php
src/Enhavo/Bundle/DoctrineExtensionBundle/Tests/EventListener/ReferenceSubscriberTest.php
src/Enhavo/Bundle/DoctrineExtensionBundle/Tests/Fixtures/Entity/Reference/NodeContainer.php

If we have a chain of node entities, which uses the `ReferenceListener`, some entities are not saved, because a lacking persist calls.

Fix persist

---

assets/node_modules/@enhavo/form/loader/PolyCollectionLoader.ts
assets/node_modules/@enhavo/form/services/loader.yaml
assets/node_modules/@enhavo/form/type/PolyCollectionType.ts

Save the expand/collapse state of the PolyCollectionType. Only the root state will be saved.

Save PolyCollection expand state

---

assets/node_modules/@enhavo/form/type/AutoSuggestType.ts
assets/node_modules/@enhavo/media/form/Media.ts
src/Enhavo/Bundle/FormBundle/Form/Type/AutoSuggestEntityType.php
src/Enhavo/Bundle/FormBundle/Form/Type/AutoSuggestType.php

* If upload was triggered via upload button the outer form submitted as well
* Fix upload a file twice after deleting
* Allow case insensitive search
* Fix return js object instead of array

Fix submitting outer form and autosuggest case insensitive

---

assets/node_modules/@enhavo/form/type/WysiwygType.ts

- If you add a link in tinymce with a domain which is the same as the browser it will be removed. This is very critical if we want to add urls for a mailing where the full domain is necessary.
- Add the code button to have more control of the code
- Add List buttons and rearrange

Fix tinymce links

---

src/Enhavo/Bundle/TranslationBundle/Resources/config/services/generator.yaml

Fix for TranslationSlugGenerator service definition missing a parameter.

[TranslationBundle] Fix for TranslationSlugGenerator service definition

---

src/Enhavo/Bundle/BlockBundle/Block/Type/VideoBlockType.php
src/Enhavo/Bundle/BlockBundle/Resources/config/services/block.yaml
src/Enhavo/Bundle/BlockBundle/Tests/Block/Type/VideoBlockTypeTest.php
src/Enhavo/Bundle/ContentBundle/Exception/VideoException.php
src/Enhavo/Bundle/ContentBundle/Resources/config/services.yaml

* Video block uses video api from `ContentBundle`

Use video api in video block

---

src/Enhavo/Bundle/UserBundle/Security/UserChecker.php
src/Enhavo/Bundle/UserBundle/Tests/Security/UserCheckerTest.php

* Don't throw exception if user has wrong type inside `UserChecker`, because if we use multiple user authenticator, with different providers a user with different type should be allowed.

Don't throw exception if user has wrong type

---

assets/node_modules/@enhavo/form/assets/styles/form.scss
assets/node_modules/@enhavo/form/assets/styles/module/_date.scss
assets/node_modules/@enhavo/form/type/DateTimeType.ts
assets/node_modules/@enhavo/form/type/DateType.ts
src/Enhavo/Bundle/ContentBundle/Form/Type/ContentType.php
src/Enhavo/Bundle/FormBundle/Form/Type/DateTimeType.php
src/Enhavo/Bundle/FormBundle/Form/Type/DateType.php
src/Enhavo/Bundle/FormBundle/Resources/views/admin/form/form/fields.html.twig
src/Enhavo/Bundle/SliderBundle/Form/Type/SlideType.php

Added option "allow_clear" (default false) to DateType and DateTimeType. If true, a button is added to the form element which will empty the form field, allowing you to clear the date.

Added button to DateType/DateTimeType to clear the date

---

assets/node_modules/@enhavo/app/assets/fonts/enhavo-icons.font.js

Add html preview file for icon font if encore/webpack is executed in dev environment

html preview for icon font in dev

---

src/Enhavo/Bundle/UserBundle/Resources/translations/EnhavoUserBundle.de.yaml

[UserBundle] Fixed reset password mail text not working in german locale

[UserBundle] Fixed reset password mail text not working in german locale

---

src/Enhavo/Bundle/ThemeBundle/EventListener/ThemeRegisterSubscriber.php

Replace doctrine DBALException, which no longer exists in doctrine, with the new doctrine/DBAL/Exception.

fix on console command

---

src/Enhavo/Bundle/AppBundle/Command/InitCommand.php
src/Enhavo/Bundle/BlockBundle/Command/CleanUpCommand.php
src/Enhavo/Bundle/BlockBundle/Command/DebugBlockUseCommand.php
src/Enhavo/Bundle/CalendarBundle/Command/ImportCommand.php
src/Enhavo/Bundle/ContentBundle/Command/SitemapDumpCommand.php
src/Enhavo/Bundle/MediaBundle/Command/CleanUpCommand.php
src/Enhavo/Bundle/MediaBundle/Command/RefreshFormatCommand.php
src/Enhavo/Bundle/MediaBundle/Command/UpdateFileCommand.php
src/Enhavo/Bundle/NewsletterBundle/Command/SendNewsletterCommand.php
src/Enhavo/Bundle/SearchBundle/Command/ElasticInstallCommand.php
src/Enhavo/Bundle/SearchBundle/Command/IndexCommand.php
src/Enhavo/Bundle/SearchBundle/Command/ReindexCommand.php
src/Enhavo/Bundle/ThemeBundle/Command/ThemeDebugCommand.php
src/Enhavo/Bundle/ThemeBundle/Command/WebpackBuildCommand.php
src/Enhavo/Bundle/UserBundle/Command/ActivateUserCommand.php
src/Enhavo/Bundle/UserBundle/Command/ChangePasswordCommand.php
src/Enhavo/Bundle/UserBundle/Command/CreateUserCommand.php
src/Enhavo/Bundle/UserBundle/Command/RoleCommand.php

Status return values were added to the commands, which were introduced in Symfony 5.

add command status return value in enhavo commands

---

src/Enhavo/Bundle/UserBundle/Resources/config/validation.yaml

Removed email validation setting which no longer exists in symfony 5

[UserBundle] Removed email validation setting

---

src/Enhavo/Bundle/UserBundle/Controller/ResetPasswordController.php
src/Enhavo/Bundle/UserBundle/Repository/UserRepository.php
src/Enhavo/Bundle/UserBundle/Validator/Constraints/UserExistsValidator.php

Changed user loading in login from deprecated repository->loadUserByUsername() to new repository->loadUserByIdentifier().
Allow login both by username and by email.

[UserBundle] Changed login to allow both username and email

---

src/Enhavo/Bundle/FormBundle/Formatter/HtmlSanitizer.php
src/Enhavo/Bundle/FormBundle/Tests/Formatter/HtmlSanitizerTest.php

| Backport    | 0.10
* Allow frame targets _blank and _self in `html_sanatize`

Allow frame targets _blank and _self

---

src/Enhavo/Bundle/ShopBundle/Resources/config/doctrine/Product.orm.xml
src/Enhavo/Bundle/ShopBundle/Resources/config/doctrine/ProductVariant.orm.xml

Remove property unique from product images join column to be able to assign multiple images to one product and vice versa.

remove property unique-id from product-picture relation

---

src/Enhavo/Bundle/ShopBundle/Manager/ProductManager.php

bugfix; findBy returns array; $resource === null is always false

bugfix; findBy returns empty array

---

src/Enhavo/Bundle/ShopBundle/Resources/views/theme/shop/cart/summary.html.twig
src/Enhavo/Bundle/ShopBundle/Resources/views/theme/shop/checkout/confirm.html.twig
src/Enhavo/Bundle/ShopBundle/Resources/views/theme/shop/checkout/login.html.twig
src/Enhavo/Bundle/ShopBundle/Resources/views/theme/shop/order/detail.html.twig
src/Enhavo/Bundle/ShopBundle/Resources/views/theme/shop/order/show.html.twig
src/Enhavo/Bundle/ShopBundle/Resources/views/theme/shop/product/show.html.twig
src/Enhavo/Bundle/ShopBundle/Resources/views/theme/shop/user/address.html.twig

| New feature?  no
Replace outdated twig function widget_render with new widget()-function in shop-bundle

replace unknown twig function widget_render with widget in shop-bundle

---

assets/node_modules/@enhavo/app/list/components/ListComponent.vue

fix warning in browser console: Property "enabled" was accessed during render but is not defined on instance.

---

assets/node_modules/@enhavo/vue-form/form/Util.ts

Returns FormData object instead of generating the object itself, causing several checkbox inputs not to be sent

return FormData in serializeForm

---

src/Enhavo/Bundle/AppBundle/View/Type/UpdateViewType.php
src/Enhavo/Bundle/ContentBundle/EventListener/UpdatedSubscriber.php
src/Enhavo/Bundle/ContentBundle/Factory/ContentFactory.php
src/Enhavo/Bundle/ContentBundle/Resources/config/doctrine/Content.orm.xml
src/Enhavo/Bundle/ContentBundle/Resources/config/services.yaml

fix created and updated are not set properly on content when created/updated via ViewTypes
created and updated are not set properly on content when created/updated via ViewTypes

Set created and updated properly on Content when created/updated via ViewTypes

---

src/Enhavo/Bundle/ArticleBundle/Resources/views/theme/resource/article/list.html.twig
src/Enhavo/Bundle/FormBundle/Tests/Twig/FormatExtensionTest.php
src/Enhavo/Bundle/FormBundle/Twig/FormatExtension.php
src/Enhavo/Bundle/SearchBundle/Resources/views/admin/search/result.html.twig
src/Enhavo/Bundle/SearchBundle/Resources/views/theme/search/result.html.twig
src/Enhavo/Bundle/SliderBundle/Resources/views/theme/widget/slider.html.twig

| Tickets       | #1543
According to #1543, there is a security issue where xss code can be executed in frontend. Enhavo already provide a twig filter `html_sanitize` to prevent xss injections, but in this case the filter is not applied to the output of the `headline` filter.  The `headline` filter is marked as html safe, which is not true. To unmark it as html safe will cause bc breaks because the output will be encoded html. So we apply the sanitize routine to the headline filter to satisfy the html safe mark.
Further outputs where checked as well and the `raw` filter was replaced with `html_sanitize` where html output from the user is expected.

Sanitize headline

---

src/Enhavo/Bundle/ArticleBundle/Resources/config/doctrine/Article.orm.xml
src/Enhavo/Bundle/BlockBundle/Resources/config/doctrine-block/Enhavo.Bundle.BlockBundle.Model.Block.PictureBlock.orm.xml
src/Enhavo/Bundle/BlockBundle/Resources/config/doctrine-block/Enhavo.Bundle.BlockBundle.Model.Block.TextPictureBlock.orm.xml
src/Enhavo/Bundle/CalendarBundle/Resources/config/doctrine/Appointment.orm.xml
src/Enhavo/Bundle/SettingBundle/Resources/config/doctrine/MediaValue.orm.xml
src/Enhavo/Bundle/TranslationBundle/Resources/config/doctrine/TranslationFile.orm.xml

could not delete files in media-library if related to article. so i searched for relations with the missing on-delete cascade rule.

add missing on-delete set null for many-to-one related files

---

src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/app/config.yml
src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/routes/admin/tag.yaml
src/Enhavo/Bundle/MediaLibraryBundle/Resources/translations/EnhavoMediaLibraryBundle.de.yaml
src/Enhavo/Bundle/MediaLibraryBundle/Resources/translations/EnhavoMediaLibraryBundle.en.yaml

before it was not possible to set permissions on listing/creation/update/deletion of media-library related tags

fix media-lib tag permissions

---

src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/doctrine.tpl.php
src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/item-doctrine.tpl.php

there was a linebreak missing when block maker created manyToOne doctrine yaml

[BlockBundle] Fix missing linebreak in make:enhavo:block

---

assets/node_modules/@enhavo/vue-form/form/Form.ts

remove stringify function in submitAsync function

---

src/Enhavo/Bundle/MediaBundle/Validator/Constraints/ClamAvValidator.php

If a daemon is used to scan for viruses, the daemon can't access tmp files because they are only allowed to r/w by www-data.

[MediaBundle] fix clamdscan cannot access tmp file

---

src/Enhavo/Bundle/FormBundle/Resources/views/admin/form/form/fields.html.twig

fix enhavo_auto_complete_entity_widget not rendering attributes

[FormBundle] fix enhavo_auto_complete_entity_widget not rendering attributes

---

assets/node_modules/@enhavo/form/components/FormListComponent.vue
assets/node_modules/@enhavo/vue-form/components/FormChoiceExpandedComponent.vue
assets/node_modules/@enhavo/vue-form/components/FormRowsComponent.vue
assets/node_modules/@enhavo/vue-form/data/FormData.ts
src/Enhavo/Bundle/FormBundle/Form/VueType/ListVueType.php
src/Enhavo/Bundle/VueFormBundle/Form/VueData.php
src/Enhavo/Bundle/VueFormBundle/Form/VueForm.php

* Vue form children are always array now. Accessing object via key can be difficult in some places. Arrays are more easy to handle, especially in adding and removing.

Vue form children  are always array now

---

assets/node_modules/@enhavo/form/type/CheckboxType.ts
assets/node_modules/@enhavo/form/type/SelectType.ts

If CheckBox or SelectType was in located a subform, count of selected checkboxes did not work properly.

[FormBundle] Find only the closest parent with attribute to count selected items

---

src/Enhavo/Bundle/UserBundle/Tests/Security/Authentication/FormLoginAuthenticatorTest.php

Add a new unit test for the onAutenticationFailure function to fix testing queue.

add authentication failure unit test

---

assets/node_modules/@enhavo/form/components/FormListComponent.vue
assets/node_modules/@enhavo/vue-form/components/FormErrorsComponent.vue
assets/node_modules/@enhavo/vue-form/components/FormRowComponent.vue

* Fix row component. The property `rowComonent` has no effect if using `form-row`for a non compund type.
* Allow to overwrite add button in form list

Fix row component

---

src/Enhavo/Bundle/AppBundle/Resources/config/services/services.yaml

| Backport      | 0.11, 0.10, 0.9
* Allow autowiring for `TokenGeneratorInterface`

Allow autowiring TokenGeneratorInterface

---

assets/node_modules/@enhavo/form/form/helper/FormListHelper.ts

* Trigger `onMove` event also on drag&drop for connected lists

Trigger onMove event also on drag&drop for connected lists

---

assets/node_modules/@enhavo/form/form/model/FormList.ts

| Tickets       | no
* fix updateIndex loop on FormList. The update index need only to go throw children and prototype otherwise it may run into loops

fix: updateIndex loop on FormList

---

src/Enhavo/Bundle/ShopBundle/Entity/OrderItem.php
src/Enhavo/Bundle/ShopBundle/EventListener/PromotionSubscriber.php
src/Enhavo/Bundle/ShopBundle/Form/Type/PromotionType.php
src/Enhavo/Bundle/ShopBundle/Manager/PromotionManager.php
src/Enhavo/Bundle/ShopBundle/Resources/config/services/form.yaml
src/Enhavo/Bundle/ShopBundle/Resources/config/services/services.yaml
src/Enhavo/Bundle/ShopBundle/Resources/config/validation.yaml
src/Enhavo/Bundle/ShopBundle/Resources/translations/messages.de.yaml
src/Enhavo/Bundle/ShopBundle/Resources/translations/messages.en.yaml

| Tickets       | no
* add `getUnitsDiscount` function to `OrderItem`
* automatic code generation for promotion form
* help text for promotion form rules und action
* fix `getUnitDiscount`, check all promotion adjustments

feat: add get units discount function and improve promotion form

---

assets/node_modules/@enhavo/media-library/Data.ts
assets/node_modules/@enhavo/media-library/components/MediaLibraryComponent.vue
src/Enhavo/Bundle/MediaBundle/Controller/UploadController.php
src/Enhavo/Bundle/MediaBundle/Event/PostUploadEvent.php
src/Enhavo/Bundle/MediaBundle/Resources/config/routes/admin/upload.yaml
src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yaml
src/Enhavo/Bundle/MediaLibraryBundle/EventListener/FileUploadSubscriber.php
src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/app/config.yml
src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/routes/admin/file.yaml
src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/routes/admin/upload.yaml
src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/routing.yml
src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/services.yml
src/Enhavo/Bundle/MediaLibraryBundle/View/Type/MediaLibraryViewType.php

Changed behaviour of media library bundle from showing all files to just files uploaded via the media library screen; reenabled media garbage collection for files not uploaded via media library; added post upload event to react to file upload including configurable event name to distinguish between different upload routes

[MediaBundle][MediaLibraryBundle] Changed behaviour of media library bundle

---

assets/node_modules/@enhavo/app/action/model/SaveAction.ts

Add the view_id to url in saveAction if url exists.  Removes the form loading screen after new enhavo transition actions

remove loading screen after shop transition action

---

assets/node_modules/@enhavo/app/compiler-pass/stimulus-controller-register.js

* fix: long stimulus controller names

fix: long stimulus controller names

---

assets/node_modules/@enhavo/app/modal/model/AjaxFormModal.ts

* Use js native form for `AjaxFormModal` instead of jQuery serialize

fix: use js native form for AjaxFormModal

---

src/Enhavo/Bundle/UserBundle/Resources/config/app/config.yaml
src/Enhavo/Bundle/UserBundle/Resources/config/routes/admin/user.yaml
src/Enhavo/Bundle/UserBundle/Resources/config/validation.yaml

* remove unique email from create update groups to easily change behavior inside a project

fix: remove unique email from create update groups

---

assets/node_modules/@enhavo/media/type/MediaConfig.ts
assets/node_modules/@enhavo/media/type/MediaRow.ts
src/Enhavo/Bundle/MediaBundle/Form/Type/MediaType.php

* fix: create template from prototype of media form. It was not checking the prototype name

fix: create template from prototype of media form

---

src/Enhavo/Bundle/TaxonomyBundle/Model/TermInterface.php

When rearanging terms in listDataView an exception occured when trying to remove an item from its parent and also when sorting items.
This already was fixed in Term->setParent but still was missing in TermInterface.

[TaxonomyBundle] TermInterface parent can't be set to null via DnD

---

src/Enhavo/Bundle/TaxonomyBundle/Entity/Term.php

Term parent can't be set to null when rearanging via DnD

---

src/Enhavo/Bundle/VueFormBundle/Form/VueType/FormVueType.php
src/Enhavo/Bundle/VueFormBundle/Resources/config/services.yaml

serialize property value in FormVueType to prevent circle references

serialize property value in FormVueType

---

src/Enhavo/Bundle/CommentBundle/Resources/config/doctrine/Comment.orm.xml

| Backport      | 0.11, 0.12
Removed cascade remove setting from comment to thread. This setting meant that deleting a comment would lead to deleting the whole comment thread, which is obviously not the intention.

[CommentBundle] Removed cascade remove from comment to thread

---

src/Enhavo/Bundle/MediaBundle/EventListener/GarbageCollectionSubscriber.php

| Backport      | 0.11, 0.12
Fixed error in GarbageCollectionSubscriber where files had id null for some reason

[MediaBundle] Fixed error in GarbageCollectionSubscriber

---

assets/node_modules/@enhavo/form/form/model/ConditionalForm.ts
assets/node_modules/@enhavo/form/form/model/ListForm.ts
assets/node_modules/@enhavo/vue-form/model/ChoiceForm.ts
assets/node_modules/@enhavo/vue-form/model/Form.ts
src/Enhavo/Bundle/VueFormBundle/Form/Extension/ChoiceVueTypeExtension.php
src/Enhavo/Bundle/VueFormBundle/Form/Extension/RadioVueTypeExtension.php
src/Enhavo/Bundle/VueFormBundle/Form/VueForm.php
src/Enhavo/Bundle/VueFormBundle/Tests/Form/Extension/ChoiceVueTypeExtensionTest.php
src/Enhavo/Bundle/VueFormBundle/Tests/Form/Extension/RadioVueTypeExtensionTest.php

Choice children, when choice has the option expanded, have different full names as other forms. In php, the `ChoiceType` will change the full name in `finishView`. So on the js site, we can't use the `updateFullName` in `ListForm`, because we assume that every full name of a form has the same build rules. So we have to delegate the rebuilding of the full name to the model, so it can overwrite its behaviour if needed.

fix: vue form with choice expanded

---

src/Enhavo/Bundle/AppBundle/Filter/Type/BetweenFilterType.php

| Backport      | 0.11, 0.12
Fixed error in BetweenFilterType

[AppBundle] Fixed error in BetweenFilterType

---

src/App/Controller/PersonController.php
src/Enhavo/Bundle/RoutingBundle/DependencyInjection/Compiler/ConditionResolverPass.php
src/Enhavo/Bundle/RoutingBundle/Request/RequestContext.php
src/Enhavo/Bundle/RoutingBundle/Resources/config/services/general.yaml

| Backport      | 0.10, 0.11, 0.12
* Make the condition resolver available in a static routes over the request context

feat: make the condition resolver available in a static routes

---

src/Enhavo/Bundle/MediaBundle/Form/Type/FileType.php

| Backport     | 0.12
* Fix `FileType`: If no parameters type is set, we should't get any errors

fix: file type if no parameters type is set

---

src/Enhavo/Component/Type/AbstractContainerType.php
src/Enhavo/Component/Type/AbstractTypeExtension.php
src/Enhavo/Component/Type/Exception/TypeNotValidException.php
src/Enhavo/Component/Type/Factory.php
src/Enhavo/Component/Type/Registry.php
src/Enhavo/Component/Type/RegistryExtension.php
src/Enhavo/Component/Type/RegistryInterface.php
src/Enhavo/Component/Type/Tests/FactoryTest.php
src/Enhavo/Component/Type/Tests/Mock/RegistryMock.php
src/Enhavo/Component/Type/Tests/RegistryTest.php
src/Enhavo/Component/Type/Tests/TypeExtensionCompilerPassTest.php
src/Enhavo/Component/Type/TypeExtensionCompilerPass.php
src/Enhavo/Component/Type/TypeExtensionInterface.php

Allow to extends type via `TypeExtensionCompilerPass`. With this compiler you are able to add extensions to the registry. The factory will pass all needed extensions to the container class to apply if neccessary.

feat: type extension

---

config/routes.yaml
src/Enhavo/Bundle/ApiBundle/Documentation/Model/Content.php
src/Enhavo/Bundle/ApiBundle/Documentation/Model/Response.php
src/Enhavo/Bundle/ApiBundle/Tests/Documentation/DocumentationTest.php

* fix showing content object in api docs
* remove examples

fix: content in api docs

---

src/Enhavo/Bundle/MultiTenancyBundle/Resolver/SessionResolver.php
src/Enhavo/Bundle/MultiTenancyBundle/Tests/Resolver/SessionResolverTest.php

| Backport     | 0.10
| Tickets      | Fix #... 
If e.g. TenantManager->getTenant was called from a CLI Command during resolver->getTenant no Request is provided in SessionResolver.
Instead of throwing an Error due to a call on a null object, return null and see if any of the remaining resolvers can resolve the tenant and finally return null if none was found.

[MultiTenancyBundle] Fix call on null error exception if Resolver is used from Command

---

composer.json
config/packages/enhavo_payment.yaml
src/Enhavo/Bundle/PaymentBundle/Resources/config/app/config.yaml

When using `bin/console` we get an error:
```
You cannot use "Http\Message\MessageFactory\GuzzleMessageFactory" as the "php-http/message-factory" package is not installed. Try running "composer require php-http/message-factory". Note that this package is deprecated, use "psr/http-factory" instead
```
This occurs if we use payum. When the payum builder run with the offline factory it will instanciate `Http\Message\MessageFactory\GuzzleMessageFactory` be default (because this class is available), but there is no `Http\Message\MessageFactory` available and that's why the error trigger.
Only in `php-http/message-factory` I could found a `MessageFactory`, in …

fix: GuzzleMessageFactory error

---

src/Enhavo/Bundle/ApiBundle/Normalizer/AbstractDataNormalizer.php
src/Enhavo/Bundle/ApiBundle/Normalizer/DataNormalizer.php
src/Enhavo/Bundle/ApiBundle/Normalizer/DataNormalizerInterface.php
src/Enhavo/Bundle/AppBundle/Normalizer/FormDataNormalizer.php
src/Enhavo/Bundle/ContentBundle/Normalizer/ContentDataNormalizer.php
src/Enhavo/Bundle/ContentBundle/Resources/config/serialization/content.yaml
src/Enhavo/Bundle/NavigationBundle/Endpoint/NavigationEndpointExtension.php
src/Enhavo/Bundle/NavigationBundle/Normalizer/NavigationNodeNormalizer.php
src/Enhavo/Bundle/NavigationBundle/Resources/config/serialization/navigation.yaml

| Feature?     | yes
* Use `endpoint.navigation` group to avoid full normalization of navigation subjects 
* Add `getSerializationGroups` and `isStopped` method to data normalizer to get more control of normalization
* Add context option `prevent_data_normalizers` to prevent data normalizer for execution

fix: normalize navigation

---

assets/node_modules/@enhavo/form/components/FormChoiceCollapsedComponent.vue

Fixed style errors in enhavo backend caused by importing select2 css a second time after the intern style corrections

[FormBundle] Fix select2 style

---

src/Enhavo/Bundle/TaxonomyBundle/Resources/config/serialization.yaml

Fix normalize term name for blocks

fix: normalize term name

---

.github/mergify.yml

Add backport label for version 0.13 for mergify

chore: add backport label for version 0.13

---

src/Enhavo/Bundle/MediaLibraryBundle/Form/Type/FileType.php
src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/services.yml

* Fix media library form file parameters, so it load same as in media bundle

fix: media library form file parameters

---

src/Enhavo/Bundle/AppBundle/Endpoint/Type/TemplateEndpointType.php
src/Enhavo/Bundle/AppBundle/Resources/config/services/services.yaml
src/Enhavo/Bundle/MediaBundle/Endpoint/Extension/MediaRoutesEndpointExtensionType.php
src/Enhavo/Bundle/MediaBundle/Endpoint/Type/TemplateFileEndpointType.php
src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yaml

* Move template file endpoint to media-bundle, because the app-bundle shouldn't have a dependency to media-bundle

fix: move template file endpoint to media-bundle

---

src/Enhavo/Bundle/UserBundle/DependencyInjection/Configuration.php

| Backport     | 0.10
Cases:
If MultiTenancyBundle wants to change from address for each tenant.
If on registration we want another from address than on confirm.

[UserBundle] Add possiblity to set from address for mails sent through user-bundle

---

src/Enhavo/Bundle/MediaBundle/Controller/ImageCropperController.php
src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yaml

Fixed container usage in ImageCropperController that no longer works with the version of Symfony

[MediaBundle] Fixed container usage in ImageCropperController

---

config/packages/vue.yaml
config/routes/enhavo_app.yaml
data/routes/app.yaml
src/App/Kernel.php
src/Enhavo/Bundle/AppBundle/DependencyInjection/Configuration.php
src/Enhavo/Bundle/AppBundle/DependencyInjection/EnhavoAppExtension.php
src/Enhavo/Bundle/AppBundle/Endpoint/Extension/VueRouteEndpointExtensionType.php
src/Enhavo/Bundle/AppBundle/Endpoint/Type/VueRoutesEndpointType.php
src/Enhavo/Bundle/AppBundle/EnhavoAppBundle.php
src/Enhavo/Bundle/AppBundle/Kernel/MicroKernelTrait.php
src/Enhavo/Bundle/AppBundle/Resources/config/routes/api/vue-routes.yaml
src/Enhavo/Bundle/AppBundle/Resources/config/services/endpoint.yaml
src/Enhavo/Bundle/AppBundle/Resources/config/services/services.yaml
src/Enhavo/Bundle/AppBundle/Routing/Loader/VueRouterRouteLoader.php
src/Enhavo/Bundle/AppBundle/Vue/RouteProvider/AbstractVueRouteProviderType.php
src/Enhavo/Bundle/AppBundle/Vue/RouteProvider/ChainVueRouteProvider.php
src/Enhavo/Bundle/AppBundle/Vue/RouteProvider/FileVueRouteProviderType.php
src/Enhavo/Bundle/AppBundle/Vue/RouteProvider/GroupHelperTrait.php
src/Enhavo/Bundle/AppBundle/Vue/RouteProvider/RouteProvider.php
src/Enhavo/Bundle/AppBundle/Vue/RouteProvider/VueRoute.php
src/Enhavo/Bundle/AppBundle/Vue/RouteProvider/VueRouteProviderInterface.php
src/Enhavo/Bundle/AppBundle/Vue/RouteProvider/VueRouteProviderTypeInterface.php
src/Enhavo/Bundle/ArticleBundle/Resources/config/services.yaml
src/Enhavo/Bundle/ArticleBundle/Vue/ArticleVueRouteProviderType.php
src/Enhavo/Bundle/PageBundle/Controller/PageController.php
src/Enhavo/Bundle/PageBundle/Endpoint/PageEndpointType.php
src/Enhavo/Bundle/PageBundle/Resources/config/services.yaml
src/Enhavo/Bundle/PageBundle/Vue/PageVueRouteProviderType.php
src/Enhavo/Bundle/RoutingBundle/Resources/config/services/general.yaml
src/Enhavo/Bundle/RoutingBundle/Vue/RoutingVueRouteProviderType.php

* Add vue router provider subsystem with type config
* Add providers for file, routing, page and article
* Use groups to define which vue routes getting loaded
* Add endpoint extension to provide routes automatically over options
* Provide vue-routes api
* Add kernel to load only template routes in template env

feat: load vue routes over provider sub system

---

src/Enhavo/Bundle/AppBundle/Resources/config/app/config.yaml

* Remove mappig types, because `json` is already supported and `enum` and `json_array` is not used in enhavo at all. Let the project add them if needed

fix: remove doctrine mapping types

---

data/routes/app.yaml
src/Enhavo/Bundle/AppBundle/Endpoint/Template/TemplateEndpointCollector.php

Fix `TemplateEndpointCollector` to deal with empty variants

fix: template collector

---

src/Enhavo/Bundle/MediaBundle/Provider/DefaultProvider.php

* Remove dependency to database for create file models. `FileFactory` has dependency to `DefaultProvider` which had `FileRepository` before

fix: remove dep to db for file factory

---

src/Enhavo/Bundle/FormBundle/Form/Type/ConditionalType.php
src/Enhavo/Bundle/FormBundle/Tests/Form/Type/ConditionalTypeTest.php

* Fix conditional type with empty key

fix: conditional type

---

src/Enhavo/Bundle/AppBundle/Endpoint/Extension/RouterEndpointExtensionType.php

fix add route to twig router if no routes was set

fix: add route if no routes was set

---

assets/node_modules/@enhavo/media-library/assets/styles.scss
assets/node_modules/@enhavo/media-library/components/MediaLibraryComponent.vue

MediaLibraryBundle file view could not be used on mobile devices below 640px max width.
TagList and FileList are now rearranged on below 767px to make it more convinient to work with.

Enhance MediaLibrary Bundle styles to be more mobile friendly.

---

src/Enhavo/Bundle/ShopBundle/Controller/ProductController.php

| Backport     | 0.11
Removed listAction from the Product Controller because this function was overwriting an important function.

Remove listAction from ProductController.

---

config/routes/admin/person.yaml
src/Enhavo/Bundle/AppBundle/Resources/skeleton/routing.tpl.php
src/Enhavo/Bundle/ArticleBundle/Resources/config/routes/admin/article.yaml
src/Enhavo/Bundle/CommentBundle/Resources/config/routes/admin/comment.yaml
src/Enhavo/Bundle/NewsletterBundle/Resources/config/routes/admin/group.yaml
src/Enhavo/Bundle/NewsletterBundle/Resources/config/routes/admin/newsletter.yaml
src/Enhavo/Bundle/PageBundle/Resources/config/routes/admin/page.yaml
src/Enhavo/Bundle/ShopBundle/Resources/config/routes/admin/product.yaml
src/Enhavo/Bundle/ShopBundle/Resources/config/routes/admin/product_association_type.yaml
src/Enhavo/Bundle/ShopBundle/Resources/config/routes/admin/product_attribute.yaml
src/Enhavo/Bundle/ShopBundle/Resources/config/routes/admin/tax_category.yaml
src/Enhavo/Bundle/ShopBundle/Resources/config/routes/admin/tax_rate.yaml
src/Enhavo/Bundle/SliderBundle/Resources/config/routes/admin/slider.yaml

Fixed missing template error in preview routes

[Multiple Bundles] Fixed missing template error in preview routes

---

src/Enhavo/Bundle/UserBundle/Controller/ChangeEmailController.php
src/Enhavo/Bundle/UserBundle/DependencyInjection/Configuration.php
src/Enhavo/Bundle/UserBundle/EventListener/NotEnabledSubscriber.php
src/Enhavo/Bundle/UserBundle/EventListener/VerificationRequiredListenerSubscriber.php
src/Enhavo/Bundle/UserBundle/User/UserManager.php

Avoid user beeing logged in after changePassword and after changeEmail if not enabled or verified (depends on configuration).
Disable autologin, enabled and verified by default.
Users not beeing enabled, either because they did not confirm their account or were disabled by admin or another mechanism.
Could login via password reset if auto_login was enabled for password reset.
To avoid it the two listeners for NotEnabled and NotVerified are now also mounted onto the preAuth event to avoid this.

Fix autologin possible for disabled/unverified users

---

src/Enhavo/Bundle/TranslationBundle/Tests/Translation/TranslationManagerTest.php
src/Enhavo/Bundle/TranslationBundle/Translation/TranslationManager.php

As suggested by gseidel, just return instead of throwing exception whilst detaching untranslated objects

[TranslationBundle] Fix unnecessary throw of Exception

---

src/Enhavo/Bundle/MediaBundle/Controller/FileController.php
src/Enhavo/Bundle/MediaBundle/Http/FileRangeResponse.php
src/Enhavo/Bundle/MediaBundle/Http/FileResponse.php

If browsers send a request containing a Range header, Controller must react with 206 and certain headers as expected.

[MediaBundle] Fix response on Range based Browser Request

---

src/Enhavo/Bundle/MediaBundle/Controller/FileController.php
src/Enhavo/Bundle/MediaBundle/Http/FileRangeResponse.php

fix wrongly configured Content-Range header that did not set size but range length as divisor.
Remove length attribute that also can be calculated in FileRangeResponse.

[MediaBundle] fix wrongly configured header

---

src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticSearchEngine.php

| Backport     | 0.14, 0.13
[SearchBundle] Implemented count method for ElasticSearchEngine

[SearchBundle] Implemented count method for ElasticSearchEngine

---

src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/services.yml

| Backport     | 0.14 0.13
Fixed missing argument to FileFactory service definition in MediaLibraryBundle

[MediaLibrary] Fixed missing argument to FileFactory service definition

---

src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticSearchEngine.php

[SearchBundle] Implemented count method for ElasticSearchEngine (Backport 0.13)

[SearchBundle] Implemented count method for ElasticSearchEngine (Backport 0.13)

---

migrations/Version20240619042720.php
src/Enhavo/Bundle/ContentBundle/Resources/config/doctrine/Content.orm.xml

| Backport     | 0.10
During a former refactoring, the Database field definition for canonicalUrl in Content entity got lost. Now it is back again.

[ContentBundle] re-add canonicalUrl to database

---

src/Enhavo/Bundle/NavigationBundle/Normalizer/NavigationContentNormalizer.php

* fix: normalize navigation content if null

fix: normalize navigation content if null

---

src/Enhavo/Bundle/SearchBundle/DependencyInjection/Configuration.php
src/Enhavo/Bundle/SearchBundle/DependencyInjection/EnhavoSearchExtension.php
src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticSearchEngine.php
src/Enhavo/Bundle/SearchBundle/Resources/config/services/elastic_search.yaml

Added option to configure ElasticSearch Index settings

[SearchBundle] Added option to configure ElasticSearch Index settings

---

src/Enhavo/Bundle/RoutingBundle/Entity/Route.php
src/Enhavo/Bundle/RoutingBundle/Tests/Route/RouteTest.php

When URL in eg. Page was set to empty via HTML form no static prefix was set at all so that the old static prefix was preserved instead of creating a new prefix via given AutoGenerator(s).

[RoutingBundle] Always set route's static prefix to empty string if prefix is falseish

---

.github/workflows/ci.yml

Removed ThemeBundle from static checks because the bundle no longer exists

Removed ThemeBundle from static checks

---

src/Enhavo/Bundle/TranslationBundle/EventListener/AccessControl.php
src/Enhavo/Bundle/TranslationBundle/Tests/EventListener/AccessControlTest.php

| Backport     | 0.12
| Tickets      | Fix #... 
AccessControl is designed to only allow access if RequestStack has a main request.
If called twice, on the second call a cached value is returned to avoid unnecessary computation.
Before the fix, access cache value was set to **true** before clarification if the call came with a Request.

[TranslationBundle] Avoid AccessControl to set access to true per default

---

assets/node_modules/@enhavo/app/modal/model/OutputStreamModal.ts

During outputstream read the modal should be updated on every iteration, but on every iteration the wrong object was written.

[AppBundle] Fix OutputStreamModal using non-proxy variable

---

src/Enhavo/Bundle/TranslationBundle/EventListener/DoctrineTranslationSubscriber.php
src/Enhavo/Bundle/TranslationBundle/Resources/config/services/translator.yaml

DoctrineTranslationSubscriber was configured to always use the same LocaleResolver instead of using the one configured in AppBundle

[TranslationBundle] Fix wrong LocaleResolver used in DoctrineTranslationSubscriber

---

src/Enhavo/Bundle/RoutingBundle/Entity/Route.php

In case one route exists with a contentId that does not exist anymore, doctrine-extension-bundle's ReferenceSubscriber is meant to also set contentclass to NULL.
In case contentClass may not be set to NULL, it is not even possible to remove the unassigned route via entityManager->remove due to error within ReferenceSubscriber.

[RoutingBundle] Allow contentClass to be set to null as defined in doctrine annotation

---

src/Enhavo/Bundle/ApiBundle/DependencyInjection/CompilerPass/DataNormalizerCompilerPass.php

During processing DataNormalizerCompilerPass, given priorities were not handed over to PriorityQueue.

[AppBundle] Add Priority to Data Normalizer register Calls

---

src/Enhavo/Bundle/AppBundle/Endpoint/Type/ErrorEndpointType.php
src/Enhavo/Bundle/AppBundle/ErrorRenderer/EnhavoErrorRenderer.php
src/Enhavo/Bundle/AppBundle/Resources/config/services/endpoint.yaml
src/Enhavo/Bundle/AppBundle/Resources/config/services/services.yaml

Add `ErrorEndpointType` and use it for error rendering to access view data on error pages

feat: error endpoint type

---

src/Enhavo/Bundle/BlockBundle/DependencyInjection/CompilerPass/BlockManagerCompilerPass.php
src/Enhavo/Bundle/BlockBundle/EnhavoBlockBundle.php
src/Enhavo/Bundle/BlockBundle/Factory/AbstractBlockFactory.php
src/Enhavo/Bundle/BlockBundle/Factory/BlockFactoryInterface.php

| Tickets      | Fix #... 
In Projects BlockFactories have to be overwritten and wired with certain services in some cases.
Until now BlockManager initiated BlockFactories mostly be new $className($modelName) because
Factory definitions were missing in the respective Container.
Now all BlockFactories implementing BlockFactoryInterface are inserted into the BlockManager's container, so that
it can use the service instead of instantiating a new Factory.

[BlockBundle] Enable Autowiring for Factories implementing BlockFactoryInterface

---

src/Enhavo/Bundle/UserBundle/DependencyInjection/Configuration.php

The configuration setting for auto_login was missing for registration confirm, although it was checked within the endpoint/controller.

[UserBundle] Fix RegistrationConfirmEndpoint asking for AutoLogin but  setting can't be influenced within project

---

assets/node_modules/@enhavo/app/action/model/AutoSaveAction.ts
assets/node_modules/@enhavo/app/manager/ResourcePreviewManager.ts
assets/node_modules/@enhavo/app/services/admin/action.yaml
config/packages/security.yaml
src/Enhavo/Bundle/AppBundle/Endpoint/Type/PreviewEndpointType.php
src/Enhavo/Bundle/ArticleBundle/Resources/config/routes/admin_api/article.yaml
src/Enhavo/Bundle/CommentBundle/Resources/config/routes/admin_api/comment.yaml
src/Enhavo/Bundle/NewsletterBundle/Endpoint/NewsletterTestEndpointType.php
src/Enhavo/Bundle/PageBundle/Resources/config/routes/admin_api/page.yaml
src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/PropertyDuplicateType.php
templates/theme/base.html.twig

* fix: replace `document.write` in preview as it is deprecated and won't work for long strings (tested in chrome)
* fix: auto save interval stop if normal save was triggered
* fix: property duplicate type accepts also array
* fix: login paths

fix: document write preview

---

src/Enhavo/Bundle/UserBundle/Security/Authentication/FormLoginAuthenticator.php

fix: user login failure if user not exists

fix: user login failure if user not exists

---

src/Enhavo/Bundle/MediaBundle/Endpoint/Type/TemplateFileEndpointType.php

[MediaBundle] Template File endpoint checksum based instead of id based

[MediaBundle] Template File endpoint checksum based instead of id based

---

assets/node_modules/@enhavo/form/form/model/ListForm.ts
assets/node_modules/@enhavo/vue-form/model/Form.ts

* fix: keep children untouched on morph list, so added children between a submit and update form will not be deleted

fix: morph list form

---

src/Enhavo/Bundle/BlockBundle/Duplicate/NodeChildCollectionType.php
src/Enhavo/Bundle/BlockBundle/Resources/config/app/config.yaml
src/Enhavo/Bundle/BlockBundle/Resources/config/services/services.yaml

[BlockBundle] Fixed duplication error when using blocks with child blocks

[BlockBundle] Fixed duplication error when using blocks with child blocks

---

src/Enhavo/Bundle/MultiTenancyBundle/Column/Type/TenantAwareUrlColumnType.php
src/Enhavo/Bundle/ResourceBundle/Resources/config/services/column.yaml
src/Enhavo/Bundle/RoutingBundle/Column/Type/UrlColumnType.php
src/Enhavo/Bundle/RoutingBundle/Resources/config/services/general.yaml

* fix: move url column type to routing bundle, because it has a dependency to the entity router

fix: url column type

---

src/Enhavo/Bundle/ResourceBundle/Duplicate/DuplicateFactory.php

* fix: duplicate on proxy classes, we have to call new on the parent class if it is a proxy

fix: duplicate on proxy classes

---

src/Enhavo/Bundle/ResourceBundle/DependencyInjection/Merge/AbstractConfigurationMerger.php
src/Enhavo/Bundle/ResourceBundle/DependencyInjection/Merge/GridConfigurationMerger.php
src/Enhavo/Bundle/ResourceBundle/DependencyInjection/Merge/InputConfigurationMerger.php
src/Enhavo/Bundle/ResourceBundle/Exception/GridException.php
src/Enhavo/Bundle/ResourceBundle/Exception/InputException.php
src/Enhavo/Bundle/ResourceBundle/Grid/GridFactory.php
src/Enhavo/Bundle/ResourceBundle/Input/InputFactory.php
src/Enhavo/Bundle/ResourceBundle/Tests/DependencyInjection/ConfigurationTest.php
src/Enhavo/Bundle/ResourceBundle/Tests/DependencyInjection/Merge/GridConfigurationMergerTest.php

* fix: merge grid and input config with missing classes, by adding default class while merging

fix: merge grid and input config with missing classes

---

src/Enhavo/Component/CleverReach/.gitignore
src/Enhavo/Component/CleverReach/Http/SymfonyAdapter.php
src/Enhavo/Component/CleverReach/Tests/Http/SymfonyAdapterTest.php
src/Enhavo/Component/CleverReach/composer.json

This PR is a copy of https://github.com/enhavo/cleverreach/pull/5
> I am a first-time user of this library, so if I misunderstood something please let me know 😉 
> 
> This small PR fixes several issues:
> 
> 1. API calls are not working because of Symfony exception "Invalid HTTP method "get", only uppercase letters are  accepted."
> 2. Dependencies for unit tests are not installed
> 3. Add minimum required PHP version
> 4. Add gitignore file

[CleverReach] Fix setup issues & make API calls work again

---

src/Enhavo/Bundle/NewsletterBundle/Client/CleverReachClient.php
src/Enhavo/Bundle/NewsletterBundle/Exception/ActivateException.php
src/Enhavo/Bundle/NewsletterBundle/Exception/UpdateException.php
src/Enhavo/Bundle/NewsletterBundle/Resources/config/services/services.yaml
src/Enhavo/Bundle/NewsletterBundle/Storage/Type/CleverReachStorageType.php
src/Enhavo/Bundle/NewsletterBundle/Tests/Storage/CleverReachTypeStorageTest.php
src/Enhavo/Component/CleverReach/ApiManager.php

Until now already existing subscribers could not be updated nor reactivated via enhavo newsletter subscription mecahnism.
From now if they subscribe again, they can update their data as well as reactivate their subscription via clicking on a freshly supplied confirmation link.

[NewsletterBundle] CleverReach Enhancements

---

assets/node_modules/@enhavo/form/package.json
assets/node_modules/@enhavo/form/wysiwyg/WysiwygConfig.ts
package.json

[FormBundle] Allow copy paste base64 image into wysiwyg editor

[FormBundle] Allow copy paste base64 image into wysiwyg editor

---

src/Enhavo/Bundle/BlockBundle/Duplicate/BlockDuplicateType.php
src/Enhavo/Bundle/BlockBundle/Duplicate/NodeChildCollectionType.php
src/Enhavo/Bundle/MediaBundle/Duplicate/Type/ContentDuplicateType.php
src/Enhavo/Bundle/MediaBundle/Duplicate/Type/FileDuplicateType.php
src/Enhavo/Bundle/MediaBundle/Duplicate/Type/FileTokenDuplicateType.php
src/Enhavo/Bundle/MediaBundle/Entity/Format.php
src/Enhavo/Bundle/MediaBundle/Resources/config/resources/file.yaml
src/Enhavo/Bundle/MediaBundle/Resources/config/resources/format.yaml
src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yaml
src/Enhavo/Bundle/ResourceBundle/Duplicate/AbstractDuplicateType.php
src/Enhavo/Bundle/ResourceBundle/Duplicate/Duplicate.php
src/Enhavo/Bundle/ResourceBundle/Duplicate/DuplicateFactory.php
src/Enhavo/Bundle/ResourceBundle/Duplicate/DuplicateTypeInterface.php
src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/BaseDuplicateType.php
src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/CloneDuplicateType.php
src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/CollectionDuplicateType.php
src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/CollectionReferenceDuplicateType.php
src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/DateTimeDuplicateType.php
src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/ModelDuplicateType.php
src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/PropertyDuplicateType.php
src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/ReferenceDuplicateType.php
src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/StringDuplicateType.php
src/Enhavo/Bundle/ResourceBundle/Resources/config/services/duplicate.yaml
src/Enhavo/Bundle/ResourceBundle/Tests/Duplicate/DuplicateFactoryTest.php

* fix: multiple duplicate by adding `isApplicable` function 
* chore: move duplicate groups to base type
* use duplicate meta for media file and copy all properties

fix: multiple and media duplicate

---

assets/node_modules/@enhavo/media/form/MediaUtil.ts

[MediaBundle] Thumbnails for webp images in MediaType

[MediaBundle] Thumbnails for webp images in MediaType

---

src/Enhavo/Bundle/ResourceBundle/Delete/DoctrineDeleteHandler.php
src/Enhavo/Bundle/ResourceBundle/Resource/ResourceManager.php
src/Enhavo/Bundle/ResourceBundle/Resources/config/services/services.yaml
src/Enhavo/Bundle/RevisionBundle/Delete/SoftDeleteHandler.php
src/Enhavo/Bundle/RevisionBundle/Event/ResourcePostSoftDeleteEvent.php
src/Enhavo/Bundle/RevisionBundle/Event/ResourcePostUndeleteEvent.php
src/Enhavo/Bundle/RevisionBundle/Event/ResourcePreSoftDeleteEvent.php
src/Enhavo/Bundle/RevisionBundle/Event/ResourcePreUndeleteEvent.php
src/Enhavo/Bundle/RevisionBundle/Resources/config/services/services.yaml
src/Enhavo/Bundle/RevisionBundle/Revision/RevisionManager.php
src/Enhavo/Bundle/RoutingBundle/EventListener/SoftDeleteListener.php
src/Enhavo/Bundle/RoutingBundle/Resources/config/services/general.yaml

If a resource with a route was deleted, then the route still exists but refer to a null object, because doctrine will filter it out. This leads to unexpected behaviour if a new route was created with the same path. So if a route, which is soft deleted will get invisible by overwriting the staticPrefix with random data and setting the condition to false.

fix: soft delete route

---

src/Enhavo/Bundle/RevisionBundle/Batch/Type/BinDeleteBatchType.php

Items are not able to delete if the doctrine revision filter is still active while flushing

fix: delete bin item

---

src/Enhavo/Bundle/MediaBundle/Storage/LocalChecksumFileStorage.php

Remove check exists on remove file, because if the same file (same checksum) is connected to an entity multiple times with different file objects, then all files may remove first from database and then the postRemove event will be triggered for each file. The first call will already remove the file, while the next will throw the not found exception.

fix: remove file
