enhavo/enhavo

- src/Enhavo/Bundle/AppBundle/Resources/public/css/theme.css
- src/Enhavo/Bundle/AppBundle/Resources/views/Resource/create.html.twig
- src/Enhavo/Bundle/AppBundle/Resources/views/Resource/update.html.twig
- src/Enhavo/Bundle/AppBundle/Viewer/CreateViewer.php
- src/Enhavo/Bundle/AppBundle/Viewer/EditViewer.php
- src/Enhavo/Bundle/ArticleBundle/Resources/config/routing/article.yml
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/routing/newsletter.yml
- src/Enhavo/Bundle/PageBundle/Resources/config/routing/page.yml
> button icons fixed

- src/Enhavo/Bundle/AppBundle/Controller/ResourceController.php
- src/Enhavo/Bundle/AppBundle/Resources/config/twig.yml
- src/Enhavo/Bundle/AppBundle/Resources/public/css/theme.css
- src/Enhavo/Bundle/AppBundle/Resources/public/js/classes/Admin.js
- src/Enhavo/Bundle/AppBundle/Resources/translations/EnhavoAppBundle.de.yml
- src/Enhavo/Bundle/AppBundle/Resources/translations/EnhavoAppBundle.en.yml
- src/Enhavo/Bundle/AppBundle/Resources/views/Generator/routing.yml.twig
- src/Enhavo/Bundle/AppBundle/Resources/views/Resource/table.html.twig
- src/Enhavo/Bundle/AppBundle/Resources/views/View/batch_action.html.twig
- src/Enhavo/Bundle/AppBundle/Twig/BatchActionRender.php
- src/Enhavo/Bundle/AppBundle/Viewer/TableViewer.php
- src/Enhavo/Bundle/ArticleBundle/Resources/config/routing/article.yml
- src/Enhavo/Bundle/CalendarBundle/Resources/config/routing/appointment.yml
- src/Enhavo/Bundle/CategoryBundle/Resources/config/routing/category.yml
- src/Enhavo/Bundle/DownloadBundle/Resources/config/routing/download.yml
- src/Enhavo/Bundle/NewsletterBundle/Controller/NewsletterController.php
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/routing/newsletter.yml
- src/Enhavo/Bundle/NewsletterBundle/Resources/translations/EnhavoNewsletterBundle.de.yml
- src/Enhavo/Bundle/NewsletterBundle/Resources/translations/EnhavoNewsletterBundle.en.yml
- src/Enhavo/Bundle/PageBundle/Controller/PageController.php
- src/Enhavo/Bundle/PageBundle/Resources/config/routing/page.yml
- src/Enhavo/Bundle/PageBundle/Resources/translations/EnhavoPageBundle.de.yml
- src/Enhavo/Bundle/PageBundle/Resources/translations/EnhavoPageBundle.en.yml
- src/Enhavo/Bundle/SliderBundle/Resources/config/routing/slide.yml
- src/Enhavo/Bundle/UserBundle/Resources/config/routing/group.yml
- src/Enhavo/Bundle/UserBundle/Resources/config/routing/user.yml
#34 Added batch action to table view
> 34 batch actions

- app/config/config_dev.yml
- app/config/parameters.yml.dist
- app/config/security.yml
- src/Enhavo/Bundle/UserBundle/Controller/ChangePasswordController.php
- src/Enhavo/Bundle/UserBundle/Controller/ResetPasswordController.php
- src/Enhavo/Bundle/UserBundle/Resources/config/routing/security.yml
- src/Enhavo/Bundle/UserBundle/Resources/config/routing/user.yml
- src/Enhavo/Bundle/UserBundle/Resources/translations/EnhavoUserBundle.de.yml
- src/Enhavo/Bundle/UserBundle/Resources/translations/EnhavoUserBundle.en.yml
- src/Enhavo/Bundle/UserBundle/Resources/views/Security/reset-password-confirm.html.twig
- src/Enhavo/Bundle/UserBundle/Resources/views/Security/reset-password-success.html.twig
- src/Enhavo/Bundle/UserBundle/Resources/views/Security/reset-password.html.twig
- src/Enhavo/Bundle/UserBundle/Resources/views/User/password.html.twig
Adding reset password functionality
> add reset password

- src/Enhavo/Bundle/AppBundle/Resources/public/css/theme.css
- src/Enhavo/Bundle/AppBundle/Viewer/TableViewer.php
- src/Enhavo/Bundle/ArticleBundle/Controller/ArticleController.php
- src/Enhavo/Bundle/ArticleBundle/Resources/config/routing/article.yml
- src/Enhavo/Bundle/ArticleBundle/Resources/translations/EnhavoArticleBundle.de.yml
- src/Enhavo/Bundle/ArticleBundle/Resources/translations/EnhavoArticleBundle.en.yml
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/routing/newsletter.yml
- src/Enhavo/Bundle/PageBundle/Resources/config/routing/page.yml
- src/Enhavo/Bundle/PageBundle/Resources/translations/EnhavoPageBundle.de.yml
- src/Enhavo/Bundle/PageBundle/Resources/translations/EnhavoPageBundle.en.yml
- Fix for batch checkbox bug (#114)
- Reactivated batch actions
- Added batch publish to articles
> 114 batch bug

- src/Enhavo/Bundle/ContentBundle/Repository/PublishRepositoryTrait.php
Fixed error when calling PublishRepositoryTrait->findPublished with parameter  as an array where only the last entry in the array would be considered
> Fixed error in PublishRepositoryTrait->findPublished

- features/navigation/node_reference.feature
- src/Enhavo/Bundle/AppBundle/EventListener/DoctrineReferenceListener.php
https://github.com/doctrine/doctrine2/issues/4004
> fix flushing while change set is empty

- src/Enhavo/Bundle/MediaBundle/Command/CleanUpCommand.php
- src/Enhavo/Bundle/MediaBundle/Command/RefreshFormatCommand.php
- src/Enhavo/Bundle/MediaBundle/Resources/config/services/command.yml
- src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yml
Added command to clean up orphaned media file database entries and files that might accumulate through unclean or partial delete/update operations
> MediaBundle: Clean orphaned files

- assets/node_modules/@enhavo/app/Action/Components/ActionComponent.vue
- assets/node_modules/@enhavo/app/Grid/Column/Components/ColumnActionComponent.vue
- assets/node_modules/@enhavo/app/Grid/Filter/Components/FilterBar.vue
- assets/node_modules/@enhavo/app/assets/styles/components/_grid.scss
- assets/node_modules/@enhavo/app/assets/styles/components/_view-table.scss
- assets/node_modules/@enhavo/media/assets/styles/_media.scss
- src/Enhavo/Bundle/MediaBundle/Resources/views/admin/form/media/item.html.twig
Table Abstand Spalten (Wenn keine Checkbox existiert) siehe Slider
Abstand zur Action Leiste zu Listen / Table sehr große wenn keine Pagination
Media Dropzone für Single Media Types zu lang
Media Type Mouseover
Filter Reset/Apply Button stylen
> Action in Grid stylen

- assets/node_modules/@enhavo/app/List/List.ts
- assets/node_modules/@enhavo/app/List/ListData.ts
- src/Enhavo/Bundle/AppBundle/Viewer/Viewer/ListViewer.php
See #782 
Added Option 'initially_expanded' to set ListDataView to collapsed/expanded initially
> add option to initially expand/collapse ListDataView

- src/Enhavo/Bundle/MediaBundle/Controller/FileController.php
max-age statement used in showFormatAction also required in showAction
> add max age statement to showAction

- src/Enhavo/Bundle/AppBundle/Action/Type/UpdateActionType.php
- src/Enhavo/Bundle/SliderBundle/Resources/config/doctrine/Slider.orm.yml
- src/Enhavo/Migration/Version20200508072423.php
> Sliderbugfixes

- src/Enhavo/Bundle/AppBundle/Controller/ArgumentResolver.php
- src/Enhavo/Bundle/AppBundle/Preview/Strategy/DynamicStrategy.php
- src/Enhavo/Bundle/AppBundle/Preview/Strategy/ServiceStrategy.php
- src/Enhavo/Bundle/AppBundle/Preview/StrategyResolver.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/services.yml
- src/Enhavo/Bundle/ArticleBundle/Controller/ArticleController.php
worked also in page->preview and newsletter->preview
> Fix: [ArticleBundle] Article Preview not working

- assets/node_modules/@enhavo/media/MediaLibrary/Components/MediaLibraryComponent.vue
- src/Enhavo/Bundle/MediaBundle/Viewer/MediaLibraryViewer.php
> Fix media library upload twice

- src/Enhavo/Bundle/ArticleBundle/Resources/config/routes/admin/category.yaml
- src/Enhavo/Bundle/ArticleBundle/Resources/config/routes/admin/tag.yaml
- src/Enhavo/Bundle/DemoBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/routes/admin/group.yaml
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/routes/admin/subscriber.yaml
- src/Enhavo/Bundle/NewsletterBundle/Resources/translations/EnhavoNewsletterBundle.en.yaml
- src/Enhavo/Bundle/RedirectBundle/Resources/config/routes/admin/redirect.yaml
> fix translations

- src/Enhavo/Bundle/RoutingBundle/Router/Strategy/SlugIdStrategy.php
- src/Enhavo/Bundle/RoutingBundle/Tests/Mock/RouteContentMock.php
- src/Enhavo/Bundle/RoutingBundle/Tests/Router/RouterTest.php
> router tests

- src/Enhavo/Bundle/BlockBundle/Resources/config/doctrine/Node.orm.xml
entries in block_xxx_block tables entries are still not removed if i do delete them directly and not by deleting the whole column.
> delete subordinary entries on delettion of a node

- src/Enhavo/Bundle/MediaBundle/EventListener/DoctrineSubscriber.php
- src/Enhavo/Bundle/MediaBundle/Media/FormatManager.php
fix nesting exception on delete formats while listening on doctrine pre remove
> fix nesting exception on delete formats

- assets/node_modules/@enhavo/dependency-injection/Loader/Loader.js
> dependency-injection loader

- src/Enhavo/Bundle/FormBundle/Formatter/CurrencyFormatter.php
- src/Enhavo/Bundle/FormBundle/Tests/Formatter/CurrencyFormatterTest.php
in case of values between -0.01 and -1.0
> fix CurrencyFormatter wrong formatting

- src/Enhavo/Bundle/ShopBundle/Cart/UserCartProvider.php
> fix merge cart function

- assets/node_modules/@enhavo/app/shims.d.ts
- assets/node_modules/@enhavo/vue-form/components/FormChoiceComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormEndComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormErrorsComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormFormComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormHelpComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormHiddenComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormLabelComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormRestComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormRowComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormStartComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormTextComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormWidgetComponent.vue
- assets/node_modules/@enhavo/vue-form/form/Form.ts
- assets/node_modules/@enhavo/vue-form/form/FormFactory.ts
- assets/node_modules/@enhavo/vue-form/form/FormFactoryInterface.ts
- assets/node_modules/@enhavo/vue-form/package.json
- src/Enhavo/Bundle/VueFormBundle/DependencyInjection/Compiler/VueTypeCompilerPass.php
- src/Enhavo/Bundle/VueFormBundle/EnhavoVueFormBundle.php
- src/Enhavo/Bundle/VueFormBundle/Exception/VueTypeException.php
- src/Enhavo/Bundle/VueFormBundle/Form/Extension/VueTypeExtension.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueData.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueForm.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/ChoiceVueType.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/FormVueType.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/HiddenVueType.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueTypeInterface.php
- src/Enhavo/Bundle/VueFormBundle/Resources/config/services.yaml
- src/Enhavo/Bundle/VueFormBundle/Tests/DependencyInjection/Compiler/VueTypeCompilerPassTest.php
Allowing new types, that will expose view data from a FormType. Also improve vue form rendering.
> VueType extensions

- src/Enhavo/Bundle/AppBundle/Controller/ModalController.php
> [AppBundle]Fixed ModalController formAction ignoring parameter template from route

- assets/node_modules/@enhavo/app/modal/factory/AjaxFormModalFactory.ts
| Backport      | -
| Tickets       | -
> [AppBundle] Minor Bugfix: Fixed class name of AjaxFormModalFactory

- src/Enhavo/Bundle/NewsletterBundle/Controller/SubscriptionController.php
- src/Enhavo/Bundle/NewsletterBundle/Tests/Controller/SubscriptionControllerTest.php
> better return status for addAction

- features/user/login.feature
- src/Enhavo/Bundle/UserBundle/Resources/translations/EnhavoUserBundle.de.yaml
- src/Enhavo/Bundle/UserBundle/Resources/translations/EnhavoUserBundle.en.yaml
- src/Enhavo/Bundle/UserBundle/Resources/views/admin/security/login/login.html.twig
- src/Enhavo/Bundle/UserBundle/Resources/views/admin/security/reset-password/confirm.html.twig
- src/Enhavo/Bundle/UserBundle/Resources/views/admin/security/reset-password/request.html.twig
Fix reset and confirm view and behat tests
> Fix login screens and tests

- src/Enhavo/Bundle/VueFormBundle/Form/VueForm.php
- src/Enhavo/Bundle/VueFormBundle/Tests/Form/VueFormTest.php
- src/Enhavo/Bundle/VueFormBundle/Tests/Form/VueTypeTestTrait.php
Implement `VueForm` `submitData`function to create submit data for a form
> Implement VueForm submitData

- .enhavo.yml
Fix subtree components. Some not exists and some are new
> Fix subtree components

- composer.json
- src/Enhavo/Bundle/NewsletterBundle/Client/CleverReachClient.php
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/NewsletterBundle/Tests/Storage/CleverReachTypeStorageTest.php
- src/Enhavo/Component/CleverReach/Http/GuzzleAdapter.php
- src/Enhavo/Component/CleverReach/Tests/Http/GuzzleAdapterTest.php
- src/Enhavo/Component/CleverReach/Tests/fixtures/server/error.php
- src/Enhavo/Component/CleverReach/Tests/fixtures/server/index.php
- src/Enhavo/Component/CleverReach/composer.json
Fix client integration into `NewsletterBundle`
> Fix cleverreach client

- assets/node_modules/@enhavo/app/action/ActionInterface.ts
- assets/node_modules/@enhavo/app/action/ActionManager.ts
- assets/node_modules/@enhavo/app/action/components/DropdownActionComponent.vue
- assets/node_modules/@enhavo/app/action/factory/DropdownActionFactory.ts
- assets/node_modules/@enhavo/app/action/factory/FilterActionFactory.ts
- assets/node_modules/@enhavo/app/action/factory/SingleFilterActionFactory.ts
- assets/node_modules/@enhavo/app/action/model/AbstractAction.ts
- assets/node_modules/@enhavo/app/action/model/DropdownAction.ts
- assets/node_modules/@enhavo/app/action/model/FilterAction.ts
- assets/node_modules/@enhavo/app/action/model/SingleFilterAction.ts
- assets/node_modules/@enhavo/app/assets/styles/view.scss
- assets/node_modules/@enhavo/app/grid/Grid.ts
- assets/node_modules/@enhavo/app/grid/GridConfiguration.ts
- assets/node_modules/@enhavo/app/grid/components/Grid.vue
- assets/node_modules/@enhavo/app/grid/filter/FilterInterface.ts
- assets/node_modules/@enhavo/app/grid/filter/FilterManager.ts
- assets/node_modules/@enhavo/app/grid/filter/components/FilterBar.vue
- assets/node_modules/@enhavo/app/grid/filter/model/AbstractFilter.ts
- assets/node_modules/@enhavo/app/services/action.yaml
- src/Enhavo/Bundle/AppBundle/Action/Type/DropdownActionType.php
- src/Enhavo/Bundle/AppBundle/Action/Type/FilterActionType.php
- src/Enhavo/Bundle/AppBundle/Filter/AbstractFilterType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/AutoCompleteEntityType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/BetweenFilterType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/BooleanType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/EntityType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/OptionType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/TextType.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/action.yaml
Reworked the filter system so that filters can be switched on/off one by one instead of always showing all filters or none at all. This will improve the visual clarity in index view, especially when there are many filters.
Additionally, a new action type "DropdownActionType" has been added, which can be used to group actions in a dropdown menu way.
> [AppBundle] Reworked filters

- assets/node_modules/@enhavo/app/Action/ActionInterface.ts
- assets/node_modules/@enhavo/app/Action/ActionManager.ts
- assets/node_modules/@enhavo/app/Action/Components/DropdownActionComponent.vue
- assets/node_modules/@enhavo/app/Action/Factory/DropdownActionFactory.ts
- assets/node_modules/@enhavo/app/Action/Factory/FilterActionFactory.ts
- assets/node_modules/@enhavo/app/Action/Factory/SingleFilterActionFactory.ts
- assets/node_modules/@enhavo/app/Action/Model/AbstractAction.ts
- assets/node_modules/@enhavo/app/Action/Model/DropdownAction.ts
- assets/node_modules/@enhavo/app/Action/Model/FilterAction.ts
- assets/node_modules/@enhavo/app/Action/Model/SingleFilterAction.ts
- assets/node_modules/@enhavo/app/Grid/Components/Grid.vue
- assets/node_modules/@enhavo/app/Grid/Filter/Components/FilterBar.vue
- assets/node_modules/@enhavo/app/Grid/Filter/FilterInterface.ts
- assets/node_modules/@enhavo/app/Grid/Filter/FilterManager.ts
- assets/node_modules/@enhavo/app/Grid/Filter/Model/AbstractFilter.ts
- assets/node_modules/@enhavo/app/Grid/Grid.ts
- assets/node_modules/@enhavo/app/Grid/GridConfiguration.ts
- assets/node_modules/@enhavo/app/assets/styles/view.scss
- assets/node_modules/@enhavo/app/services/action.yaml
- src/Enhavo/Bundle/AppBundle/Action/Type/DropdownActionType.php
- src/Enhavo/Bundle/AppBundle/Action/Type/FilterActionType.php
- src/Enhavo/Bundle/AppBundle/Filter/AbstractFilterType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/AutoCompleteEntityType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/BetweenFilterType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/BooleanType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/EntityType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/OptionType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/TextType.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/action.yaml
Backport of Filter Rework for Version 0.9
> 0.9 app filter changes

- assets/node_modules/@enhavo/app/Grid/Filter/Components/FilterBetweenComponent.vue
- assets/node_modules/@enhavo/app/Grid/Filter/Components/FilterDateBetweenComponent.vue
- assets/node_modules/@enhavo/app/Grid/Filter/Model/BetweenFilter.ts
- src/Enhavo/Bundle/AppBundle/Filter/Type/BetweenFilterType.php
Backport of PR #1249 for version 0.9
> Fixed label of filters type BetweenFilterType displayed as json

- docs/source/guides/migration/index.rst
- docs/source/guides/migration/migrate-to-0.10.rst
- package.json
Add migration guide to to upgrade to enhavo `0.10`
> Update migration guide

- assets/node_modules/@enhavo/vue-form/form/Form.ts
- assets/node_modules/@enhavo/vue-form/form/Util.ts
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/FormVueType.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/TextareaVueType.php
- src/Enhavo/Bundle/VueFormBundle/Resources/config/services.yaml
- src/Enhavo/Bundle/VueFormBundle/Tests/Form/VueFormTest.php
Expose default form data for rendering vue forms
> Expose default form data for rendering vue forms

- assets/node_modules/@enhavo/vue-form/components/FormSimpleComponent.vue
> Fix form value

- src/Enhavo/Bundle/AppBundle/Resources/config/services/controller.yaml
- src/Enhavo/Bundle/AppBundle/Resources/config/services/services.yaml
Add aliases to simplify autowiring in projects
> Add aliases to simplify autowiring

- src/Enhavo/Bundle/AppBundle/Column/Type/StateType.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/column.yaml
| Bug fix?      |no
| Backport      | 0.9 
Add `state` column type
> Add state column type

- src/Enhavo/Bundle/MediaBundle/Twig/MediaExtension.php
> Fix media twig function accept null (#1299)

- src/Enhavo/Bundle/AppBundle/DependencyInjection/Compiler/SyliusCompilerPass.php
- src/Enhavo/Bundle/NavigationBundle/Form/Type/NodeCollectionType.php
- src/Enhavo/Bundle/NavigationBundle/Resources/config/services.yaml
> Navigationnodetype

- src/Enhavo/Bundle/TranslationBundle/Resources/config/services/translator.yaml
- src/Enhavo/Bundle/TranslationBundle/Tests/Translator/Media/FileTranslatorTest.php
- src/Enhavo/Bundle/TranslationBundle/Tests/Translator/Route/RouteTranslatorTest.php
- src/Enhavo/Bundle/TranslationBundle/Tests/Translator/Text/TextTranslatorTest.php
- src/Enhavo/Bundle/TranslationBundle/Translator/AbstractTranslator.php
- src/Enhavo/Bundle/TranslationBundle/Translator/Media/FileTranslator.php
- src/Enhavo/Bundle/TranslationBundle/Translator/Route/RouteTranslator.php
- src/Enhavo/Bundle/TranslationBundle/Translator/Text/TextTranslator.php
Fix default locale. Should use locale provider instead of configuration
> Fix default locale

- src/Enhavo/Bundle/UserBundle/Command/RoleCommand.php
- src/Enhavo/Bundle/UserBundle/Resources/config/services/command.yaml
Add `enhavo:user:role` command to adding and remove roles
> Add user role command

- src/Enhavo/Bundle/PageBundle/Resources/config/doctrine/Page.orm.xml
Set parent to null if parent page was deleted
> Fix delete parent page

- assets/node_modules/@enhavo/vue-form/components/FormChoiceCollapsedComponent.vue
Fix vue form select. The model was not updating after changing the select field
> Fix vue select model

- src/Enhavo/Bundle/TranslationBundle/EventListener/DoctrineTranslationSubscriber.php
- src/Enhavo/Bundle/TranslationBundle/Translator/Media/FileTranslator.php
- src/Enhavo/Bundle/TranslationBundle/Translator/Route/RouteTranslator.php
- src/Enhavo/Bundle/TranslationBundle/Translator/Text/TextTranslator.php
> Fix TranslationBundle Flush Issues

- src/Enhavo/Bundle/NavigationBundle/Tests/Voter/LinkVoterTest.php
- src/Enhavo/Bundle/NavigationBundle/Voter/LinkVoter.php
| Backport      | 0.9 0.10
fixed link voter base url
> fix link voter

- docs/source/reference/form/currency.rst
Added small documentation for Enhavo currency type
> docu enhavo currency form type

- src/Enhavo/Bundle/FormBundle/Form/Extension/ActionExtension.php
- src/Enhavo/Bundle/FormBundle/Form/Extension/ChoiceTypeExtension.php
- src/Enhavo/Bundle/FormBundle/Form/Extension/EntityTypeExtension.php
> fix static property of getExtendedTypes function

- src/Enhavo/Bundle/FormBundle/Controller/AutoCompleteController.php
- src/Enhavo/Bundle/FormBundle/Resources/config/services/controller.yaml
| Bug fix?      | yes/no
| New feature?  | yes/no
| Backport      | 0.9 
> parse auto-complete route-parameters

- config/packages/enhavo_block.yaml
- src/Enhavo/Bundle/BlockBundle/Maker/BlockName.php
- src/Enhavo/Bundle/BlockBundle/Maker/MakeBlock.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/doctrine.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/entity.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/form-type.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/item-doctrine.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/item-entity.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/item-factory.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/item-form-type.tpl.php
> add possibility to add items

- src/Enhavo/Bundle/AppBundle/Mailer/MailerManager.php
- src/Enhavo/Bundle/AppBundle/Mailer/Message.php
- src/Enhavo/Bundle/NewsletterBundle/Newsletter/NewsletterManager.php
Parse parameters for newsletters
> Fix newsletter parameters

- src/Enhavo/Bundle/NavigationBundle/Resources/views/theme/navigation/submenu.html.twig
> Fix submenu element

- src/Enhavo/Bundle/SidebarBundle/Resources/config/services.yaml
- src/Enhavo/Bundle/SidebarBundle/Resources/views/theme/widget/sidebar.html.twig
- src/Enhavo/Bundle/SidebarBundle/Widget/SidebarWidgetType.php
> add SidebarWidgetType

- docs/source/reference/index.rst
- docs/source/reference/validation/hierarchy-not-circular.rst
- docs/source/reference/validation/index.rst
- docs/source/reference/validation/option/message.rst
- docs/source/reference/validation/option/parent_property.rst
- src/Enhavo/Bundle/PageBundle/Resources/config/validation.yaml
Add hierarchy not circular validation docs
> Add hierarchy not circular documentation

- src/Enhavo/Bundle/UserBundle/Resources/views/admin/security/reset-password/confirm.html.twig
Fixed text error in password recovery form
> [UserBundle] Fixed text error in password recovery form

- assets/node_modules/@enhavo/form/loader/AutoSuggestLoader.ts
- assets/node_modules/@enhavo/form/services/loader.yaml
- assets/node_modules/@enhavo/form/type/AutoSuggestType.ts
- assets/node_modules/@enhavo/media/form/Media.ts
- src/App/Controller/PersonController.php
- src/App/Migration/Version20211101221431.php
- src/Enhavo/Bundle/MediaBundle/Resources/views/theme/form.html.twig
| Bug fix?      | yes/no
* Fix AutoSuggestType dependencies (remove unnecessary)
* Fix Media remove button
* Fix migrations and person admin for testing
> Fix AutoSuggestType dependencies and Media remove button

- .gitignore
- src/Enhavo/Bundle/ContentBundle/Command/SitemapDumpCommand.php
- src/Enhavo/Bundle/ContentBundle/Resources/config/services.yaml
Add sitemap dump command to optimize loading for bigger sitemap
> Sitemap dump command

- src/Enhavo/Bundle/AppBundle/Exception/TokenExpiredException.php
- src/Enhavo/Bundle/NewsletterBundle/Client/MailjetClient.php
- src/Enhavo/Bundle/NewsletterBundle/Controller/SubscriptionController.php
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/services/strategy.yaml
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/validation.yaml
- src/Enhavo/Bundle/NewsletterBundle/Storage/Type/MailjetStorageType.php
- src/Enhavo/Bundle/NewsletterBundle/Strategy/Type/DoubleOptInStrategyType.php
- src/Enhavo/Bundle/NewsletterBundle/Tests/Strategy/StrategyDoubleOptInTypeTest.php
* Fix mailjet exists method
* Fix newsletter messages
* Add TokenExpired exception
> Fix newsletter messages and mailjet exists

- src/Enhavo/Bundle/SearchBundle/Command/ElasticInstallCommand.php
- src/Enhavo/Bundle/SearchBundle/Controller/SearchConfiguration.php
- src/Enhavo/Bundle/SearchBundle/Controller/SearchController.php
- src/Enhavo/Bundle/SearchBundle/DependencyInjection/Configuration.php
- src/Enhavo/Bundle/SearchBundle/DependencyInjection/EnhavoSearchExtension.php
- src/Enhavo/Bundle/SearchBundle/Elastic/ElasticManager.php
- src/Enhavo/Bundle/SearchBundle/Indexer/Indexer.php
- src/Enhavo/Bundle/SearchBundle/Resources/config/routes/admin/admin.yaml
- src/Enhavo/Bundle/SearchBundle/Resources/config/routes/theme/theme.yaml
- src/Enhavo/Bundle/SearchBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/SearchBundle/Resources/views/theme/search/result.html.twig
* Fix result and add more options to the route
* Result templates managed by TemplateManager
* Add elastic version as configuration
> Fix search result and add elastic version

- composer.json
- src/Enhavo/Bundle/NewsletterBundle/Client/MailChimpClient.php
- src/Enhavo/Bundle/NewsletterBundle/Storage/Type/MailChimpStorageType.php
- src/Enhavo/Bundle/NewsletterBundle/composer.json
> make mailchimp client work

- assets/node_modules/@enhavo/media/form/Media.ts
- bin/behat
- bin/phpunit
If file was removed and add again, the index counter didn't increase which lead the form to think there was no changes.
> Fix media form upload

- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/doctrine.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/item-doctrine.tpl.php
> Fix cascade

- src/Enhavo/Bundle/BlockBundle/Maker/Generator/PhpClass.php
- src/Enhavo/Bundle/BlockBundle/Maker/Generator/PhpClassProperty.php
> fix remover, disable adder/remover if no singular set.

- assets/node_modules/@enhavo/dependency-injection/README.md
> fix some typos

- src/Enhavo/Bundle/AppBundle/composer.json
- src/Enhavo/Bundle/ArticleBundle/composer.json
- src/Enhavo/Bundle/BlockBundle/composer.json
- src/Enhavo/Bundle/CalendarBundle/composer.json
- src/Enhavo/Bundle/CommentBundle/composer.json
- src/Enhavo/Bundle/ContactBundle/composer.json
- src/Enhavo/Bundle/ContentBundle/composer.json
- src/Enhavo/Bundle/DashboardBundle/composer.json
- src/Enhavo/Bundle/DoctrineExtensionBundle/composer.json
- src/Enhavo/Bundle/FormBundle/composer.json
- src/Enhavo/Bundle/MediaBundle/composer.json
- src/Enhavo/Bundle/MultiTenancyBundle/composer.json
- src/Enhavo/Bundle/NavigationBundle/composer.json
- src/Enhavo/Bundle/NewsletterBundle/composer.json
- src/Enhavo/Bundle/PageBundle/composer.json
- src/Enhavo/Bundle/PaymentBundle/composer.json
- src/Enhavo/Bundle/RedirectBundle/composer.json
- src/Enhavo/Bundle/RoutingBundle/composer.json
- src/Enhavo/Bundle/SearchBundle/composer.json
- src/Enhavo/Bundle/SettingBundle/composer.json
- src/Enhavo/Bundle/ShopBundle/composer.json
- src/Enhavo/Bundle/SidebarBundle/composer.json
- src/Enhavo/Bundle/SliderBundle/composer.json
- src/Enhavo/Bundle/TaxonomyBundle/composer.json
- src/Enhavo/Bundle/TemplateBundle/composer.json
- src/Enhavo/Bundle/ThemeBundle/composer.json
- src/Enhavo/Bundle/TranslationBundle/composer.json
- src/Enhavo/Bundle/UserBundle/composer.json
- src/Enhavo/Bundle/VueFormBundle/composer.json
* Sync composer.json in php packages
> Sync composer.json in php packages

- src/Enhavo/Bundle/ShopBundle/composer.json
* Remove resource bundle from shop dependencies
> Remove resource bundle from shop dependencies

- src/Enhavo/Bundle/NewsletterBundle/Client/MailjetClient.php
- src/Enhavo/Bundle/NewsletterBundle/Storage/Type/MailjetStorageType.php
- src/Enhavo/Bundle/NewsletterBundle/composer.json
> Mailjet gdpr2

- assets/node_modules/@enhavo/app/package.json
* Add file loader for webpack copy files
> Add file loader for webpack copy files

- assets/node_modules/@enhavo/app/state/StateManager.ts
- assets/node_modules/@enhavo/app/view-stack/ViewStack.ts
- assets/node_modules/@enhavo/app/view-stack/components/IframeViewComponent.vue
- assets/node_modules/@enhavo/app/view-stack/components/ViewComponent.vue
Fixed errors in ViewStack and History pushState
> [AppBundle] Fixed errors in ViewStack and History pushState

- assets/node_modules/@enhavo/app/grid/column/components/Row.vue
- assets/node_modules/@enhavo/app/grid/filter/components/FilterDateBetweenComponent.vue
- assets/node_modules/@enhavo/app/grid/filter/components/FilterDropdownComponent.vue
- assets/node_modules/@enhavo/app/package.json
- assets/node_modules/@enhavo/app/services/vue.yaml
- docs/source/reference/filter/date-between-filter.rst
- package.json
- src/Enhavo/Bundle/AppBundle/Filter/Type/AutoCompleteEntityType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/EntityType.php
- src/Enhavo/Bundle/MultiTenancyBundle/Filter/TenancyFilterType.php
- src/Enhavo/Bundle/TaxonomyBundle/Filter/TaxonomyFilterType.php
Fixed errors in filters/grid due to php8/vue3 update
> Fixed errors in filters/grid due to php8/vue3 update

- src/Enhavo/Bundle/AppBundle/View/Type/CreateViewType.php
- src/Enhavo/Bundle/AppBundle/View/Type/UpdateViewType.php
Fixed form validation errors not displayed
> [AppBundle] Fixed form validation errors not displayed

- .enhavo.yml
- src/Enhavo/Bundle/ShopBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/TaxonomyBundle/Repository/TermRepository.php
* Fix route generator for product 
* Add slug finder for terms
> Fix route generator for product and add slug finder for terms

- src/Enhavo/Bundle/ShopBundle/Form/Type/ProductType.php
- src/Enhavo/Bundle/ShopBundle/Form/Type/TagType.php
Fix for copy/paste errors in taxonomy routes in ShopBundle
> [ShopBundle] Fix for copy/paste errors in taxonomy routes

- src/Enhavo/Bundle/ShopBundle/Entity/Product.php
- src/Enhavo/Bundle/ShopBundle/Form/Type/ProductType.php
- src/Enhavo/Bundle/ShopBundle/Resources/config/routes/admin/product.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/views/admin/resource/product/product.html.twig
Changed Product to use flag "enabled" instead of "active"
> [ShopBundle] Changed Product to use flag enabled instead of active

- src/Enhavo/Bundle/ShopBundle/Entity/Product.php
- src/Enhavo/Bundle/ShopBundle/Entity/ProductVariant.php
- src/Enhavo/Bundle/ShopBundle/Form/Type/ProductType.php
- src/Enhavo/Bundle/ShopBundle/Form/Type/ProductVariantType.php
- src/Enhavo/Bundle/ShopBundle/Resources/config/doctrine/Product.orm.xml
- src/Enhavo/Bundle/ShopBundle/Resources/config/doctrine/ProductVariant.orm.xml
- src/Enhavo/Bundle/ShopBundle/Resources/translations/EnhavoShopBundle.de.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/translations/EnhavoShopBundle.en.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/views/admin/resource/product-variant/customize.html.twig
- src/Enhavo/Bundle/ShopBundle/Resources/views/admin/resource/product/product.html.twig
Important attribute description to product and product variant model in ShopBundle added.
> add attribute description to Product and ProductVariant

- assets/node_modules/@enhavo/app/assets/styles/view.scss
Fix for style of autocomplete filter type
> [AppBundle] Fix for style of autocomplete filter type

- src/Enhavo/Bundle/AppBundle/Filter/FilterQuery.php
Fix for serious FilterQuery error
> [AppBundle] Fix for serious FilterQuery error

- assets/node_modules/@enhavo/app/assets/styles/components/_grid.scss
- assets/node_modules/@enhavo/app/assets/styles/view.scss
- assets/node_modules/@enhavo/app/grid/filter/components/FilterAutoCompleteComponent.vue
- assets/node_modules/@enhavo/app/grid/filter/components/FilterBar.vue
- assets/node_modules/@enhavo/app/grid/filter/components/FilterBetweenComponent.vue
- assets/node_modules/@enhavo/app/grid/filter/components/FilterCheckboxComponent.vue
- assets/node_modules/@enhavo/app/grid/filter/components/FilterDateBetweenComponent.vue
- assets/node_modules/@enhavo/app/grid/filter/components/FilterDropdownComponent.vue
- assets/node_modules/@enhavo/app/grid/filter/components/FilterTextComponent.vue
- src/Enhavo/Bundle/AppBundle/Resources/translations/javascript.de.yml
- src/Enhavo/Bundle/AppBundle/Resources/translations/javascript.en.yml
> [AppBundle] Changed styles for filters

- composer.json
- src/Enhavo/Bundle/AppBundle/composer.json
> add pagerfanta/pagerfanta as bugfix in sylius-resource-bundle

- src/Enhavo/Bundle/AppBundle/Resources/config/services/view.yaml
- src/Enhavo/Bundle/AppBundle/View/Type/FormViewType.php
- src/Enhavo/Bundle/UserBundle/Controller/ChangePasswordController.php
- src/Enhavo/Bundle/UserBundle/Controller/SecurityController.php
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/admin/change-password.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/services/controller.yaml
- src/Enhavo/Bundle/UserBundle/Resources/translations/EnhavoUserBundle.de.yaml
- src/Enhavo/Bundle/UserBundle/Resources/translations/EnhavoUserBundle.en.yaml
- src/Enhavo/Bundle/UserBundle/Resources/views/theme/security/reset-password/finish.html.twig
> Fix User Bundle

- src/Enhavo/Bundle/MediaBundle/composer.json
> Fix media bundle requirements

- .github/workflows/ci.yml
- src/Enhavo/Bundle/MediaLibraryBundle/composer.json
* Add composer validation checks for packages
> Add composer validation checks for packages

- src/Enhavo/Bundle/AppBundle/Tests/Fixtures/Mail/MailManager/simple-mail.html.twig
- src/Enhavo/Bundle/FormBundle/Resources/views/admin/form/form/fields.html.twig
- src/Enhavo/Bundle/MediaBundle/Resources/views/admin/form/media/media.html.twig
> fix twig deprecations

- assets/node_modules/@enhavo/media-library/components/MediaLibraryComponent.vue
- assets/node_modules/@enhavo/media-library/loader/MediaLibraryLoader.ts
- assets/node_modules/@enhavo/media/type/MediaType.ts
- package.json
- src/Enhavo/Bundle/MediaBundle/Factory/FileFactory.php
- src/Enhavo/Bundle/MediaBundle/Resources/config/doctrine/File.orm.xml
> Fix file upload

- assets/node_modules/@enhavo/media-library/MediaLibrary.ts
- assets/node_modules/@enhavo/media-library/components/Pagination.vue
- src/Enhavo/Bundle/MediaLibraryBundle/View/Type/FilesViewType.php
> fix-missing-page-option

- assets/node_modules/@enhavo/app/package.json
- assets/theme/other/base.ts
- assets/theme/other/container.di.yaml
- assets/theme/other/container.di.yaml.d.ts
- assets/theme/other/entrypoints/base.ts
- assets/theme/other/webpack.config.js
* Integrate bootstrapping for other theme assets
* Add stimulus dependency to enhavo/app
> Integrate bootstrapping for other theme assets

- assets/node_modules/@enhavo/app/compiler-pass/stimulus-controller-register.js
- assets/node_modules/@enhavo/app/compiler-pass/stimulus-register.js
- assets/node_modules/@enhavo/app/list/List.ts
- assets/node_modules/@enhavo/app/menu/MenuManager.ts
- assets/node_modules/@enhavo/app/services/enhavo/controllers.yaml
- assets/node_modules/@enhavo/app/services/enhavo/services.yaml
- assets/node_modules/@enhavo/dependency-injection/container/CompilerPass.js
- assets/node_modules/@enhavo/dependency-injection/container/ContainerBuilder.js
- assets/node_modules/@enhavo/dependency-injection/loader/Loader.js
- assets/node_modules/@enhavo/shop/services/theme/services.yaml
- assets/theme/base/container.di.yaml
* Add compiler pass to automatically detect stimulus controller inside a directory
* Fix list items creation
* Pass context to compiler pass
* Add priority to compiler pass
> Add stimulus controller register compiler pass

- assets/node_modules/@enhavo/dependency-injection/loader/Loader.js
> Fix checkGlobDirExists

- assets/node_modules/@enhavo/app/view-stack/ViewStack.ts
- assets/node_modules/@enhavo/app/view-stack/factory/ViewFactory.ts
Fixed bug in javascript when reloading a page with open views in state
> [AppBundle] Fixed bug in javascript when reloading a page

- .scrutinizer.yml
- src/Enhavo/Bundle/AppBundle/composer.json
* fix pagerfanta dependencies
* fix scrutinizer build
> fix: pagerfanta dependencies, fix scrutinizer build

- assets/node_modules/@enhavo/media-library/Data.ts
- assets/node_modules/@enhavo/media-library/MediaLibrary.ts
- assets/node_modules/@enhavo/media-library/components/Pagination.vue
- src/Enhavo/Bundle/MediaLibraryBundle/Controller/FileController.php
- src/Enhavo/Bundle/MediaLibraryBundle/Menu/MediaLibraryMenu.php
- src/Enhavo/Bundle/MediaLibraryBundle/Menu/TagMenuType.php
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/app/config.yml
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/routes/admin/file.yaml
- src/Enhavo/Bundle/MediaLibraryBundle/View/Type/MediaLibraryViewType.php
Fix Permissions to be used if user has a group
Fix ViewType to use Limit from RequestConfiguration
Make Pagination show 3 pages only and have previous/next button
> Media Library: Permissions / Limit / Pagination

- SECURITY.md
| Tickets       | Fix #1546 
Add security policies for enhavo
> Add Security policies

- assets/node_modules/@enhavo/media-library/assets/styles.scss
- src/Enhavo/Bundle/MediaLibraryBundle/Menu/TagMenuType.php
quickfix on permissions and z-index of thumbnails
> quickfix on permissions and z-index of thumbnails

- assets/node_modules/@enhavo/media-library/MediaLibrary.ts
- assets/node_modules/@enhavo/media-library/components/MediaLibraryComponent.vue
- src/Enhavo/Bundle/MediaLibraryBundle/Controller/FileController.php
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/routes/admin/file.yaml
- src/Enhavo/Bundle/MediaLibraryBundle/View/Type/FilesViewType.php
set initial sort column from route configuration
> set initial sort column from route configuration

- assets/node_modules/@enhavo/media/type/MediaItem.ts
- src/Enhavo/Bundle/MediaLibraryBundle/Controller/FileController.php
thumbnails were not shown after file selected from MediaLibrary
also make code more understandable in MediaType.ts
> fix thumbnail not working after selecting from ML

- src/Enhavo/Bundle/AppBundle/Resource/ResourceManager.php
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/app/config.yml
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/translations/EnhavoMediaLibraryBundle.de.yaml
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/translations/EnhavoMediaLibraryBundle.en.yaml
fix some translations in MediaLibraryBundle
fix ResourceManager returning wrong type of FactoryInterface
fix some translations in MediaLibraryBundle
> fix ResourceManager returning wrong type

- assets/node_modules/@enhavo/media-library/assets/styles.scss
- assets/node_modules/@enhavo/media-library/components/ListView.vue
- assets/node_modules/@enhavo/media-library/components/MediaLibraryComponent.vue
- assets/node_modules/@enhavo/media-library/components/ThumbnailView.vue
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/translations/javascript.de.yaml
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/translations/javascript.en.yaml
ui fixes
show upload progress
better feedback on failed upload
> MediaLibrary progress bar

- src/Enhavo/Bundle/RedirectBundle/Redirect/RedirectManager.php
Prioritize routes from redirects before any other
> [RedirectBundle]Prioritize routes from redirects before any other

- .enhavo.yml
* Add payment assets to enhavo ci
> Add payments assets

- src/Enhavo/Bundle/ContentBundle/Model/Video.php
- src/Enhavo/Bundle/ContentBundle/Tests/Video/YoutubeProviderTest.php
- src/Enhavo/Bundle/ContentBundle/Video/VimeoProvider.php
- src/Enhavo/Bundle/ContentBundle/Video/YoutubeProvider.php
> [ContentBundle] YouTube short URLs

- src/Enhavo/Bundle/BlockBundle/Resources/views/theme/block/video.html.twig
> Fix video embed link

- src/Enhavo/Bundle/ContentBundle/Resources/views/theme/resource/content/meta.html.twig
> [ContentBundle] fix wrong var used in ogimage

- assets/node_modules/@enhavo/media/image-cropper/ImageCropperApp.ts
- src/Enhavo/Bundle/MediaBundle/Controller/ImageCropperController.php
- src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yaml
- src/Enhavo/Bundle/MediaBundle/View/Type/ImageCropperViewType.php
> [MediaBundle]Fixed image cropper

- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/entity.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/item-entity.tpl.php
> [BlockBundle] remove unnecessary OrderBy for loop

- assets/node_modules/@enhavo/app/view-stack/ViewStack.ts
- assets/node_modules/@enhavo/app/view-stack/components/ViewComponent.vue
- assets/node_modules/@enhavo/app/view-stack/event/MaximizeEvent.ts
- assets/node_modules/@enhavo/app/view-stack/event/MinimizeEvent.ts
Added events to minimize/maximize view
> [App] Added events to minimize/maximize view

- assets/node_modules/@enhavo/app/ViewStack/ArrangeManager.ts
[AppBundle] Revised automatic arrangement and minimization of views
> [AppBundle] Revised automatic arrangement and minimization of views

- assets/node_modules/@enhavo/media/type/MediaType.ts
Fixed upload button of media type trying to submit the form
> [MediaBundle] Fixed upload button of media type trying to submit the form

- assets/node_modules/@enhavo/form/loader/ActionLoader.ts
[FormBundle] Fixed form action buttons not working
> [FormBundle] Fixed form action buttons not working

- src/Enhavo/Bundle/BlockBundle/Maker/BlockDefinition.php
- src/Enhavo/Bundle/BlockBundle/Maker/Generator/DoctrineOrmField.php
- src/Enhavo/Bundle/BlockBundle/Maker/Generator/PhpClass.php
- src/Enhavo/Bundle/BlockBundle/Maker/Generator/PhpClassProperty.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/entity.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/item-entity.tpl.php
make primary key and implements configurable for sub classes
> [BlockMaker] make primary key and implements configurable for sub classes

- src/Enhavo/Bundle/UserBundle/Resources/config/routes/user/security.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/services/services.yaml
* Fix configuration key for user login
* Make service compatible to authentication manager
> Fix configuration key and make service compatible to authentication manager

- src/Enhavo/Bundle/ShopBundle/Resources/views/admin/resource/order/order.html.twig
* Fixed Order Detail View in Admin Page
> view for order admin page

- src/Enhavo/Bundle/ShopBundle/Model/ProductVariantProxy.php
- src/Enhavo/Bundle/ShopBundle/Model/ProductVariantProxyInterface.php
- src/Enhavo/Bundle/ShopBundle/Repository/OrderRepository.php
* Add variant full title property to proxy
* Add findCheckoutOrdersBetween method to repository
> Variant full title

- src/Enhavo/Bundle/MediaBundle/Http/FileResponse.php
> Add FileResponse class

- .scrutinizer.yml
- assets/node_modules/@enhavo/block/assets/styles/block/text-picture.scss
- assets/node_modules/@enhavo/media-library/assets/styles.scss
- assets/node_modules/@enhavo/shop/assets/styles/block/product-list.scss
- assets/node_modules/@enhavo/shop/assets/styles/shop/show-product.scss
- bin/coverage
- phpunit.xml.dist
* Fix test coverage
* Migrate phpunit config
> Fix test coverage

- .scrutinizer.yml
> Fix scrutinizer analysis

- src/App/Migration/Version20220810091527.php
- src/Enhavo/Bundle/ContentBundle/Resources/translations/EnhavoContentBundle.de.yaml
- src/Enhavo/Bundle/ContentBundle/Resources/translations/EnhavoContentBundle.en.yaml
- src/Enhavo/Bundle/ContentBundle/Resources/views/admin/resource/content/meta.html.twig
- src/Enhavo/Bundle/RoutingBundle/Router/Strategy/RoutableStrategy.php
- src/Enhavo/Bundle/ShopBundle/Controller/ProductController.php
- src/Enhavo/Bundle/ShopBundle/Entity/Product.php
- src/Enhavo/Bundle/ShopBundle/Entity/ProductVariant.php
- src/Enhavo/Bundle/ShopBundle/Form/Type/ProductVariantType.php
- src/Enhavo/Bundle/ShopBundle/Manager/ProductManager.php
- src/Enhavo/Bundle/ShopBundle/Model/ProductAccessInterface.php
- src/Enhavo/Bundle/ShopBundle/Model/ProductAccessTrait.php
- src/Enhavo/Bundle/ShopBundle/Model/ProductVariantInterface.php
- src/Enhavo/Bundle/ShopBundle/Model/ProductVariantProxy.php
- src/Enhavo/Bundle/ShopBundle/Product/ProductVariantResolverInterface.php
- src/Enhavo/Bundle/ShopBundle/Product/SlugProductVariantResolver.php
- src/Enhavo/Bundle/ShopBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/config/app/search.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/config/doctrine/ProductVariant.orm.xml
- src/Enhavo/Bundle/ShopBundle/Resources/config/routes/admin/product_variant.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/translations/EnhavoShopBundle.de.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/translations/EnhavoShopBundle.en.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/views/admin/resource/product-variant/customize.html.twig
- src/Enhavo/Bundle/ShopBundle/Resources/views/admin/resource/product-variant/dimension.html.twig
- src/Enhavo/Bundle/ShopBundle/Resources/views/admin/resource/product-variant/product-variant.html.twig
- src/Enhavo/Bundle/ShopBundle/Routing/ProductVariantStrategy.php
* Add overwrite properties for variant
* Add routing strategy for variant
* Resolve variant in product action
> Add overwrite properties and routing for variant

- src/Enhavo/Bundle/AppBundle/Batch/AbstractBatchType.php
- src/Enhavo/Bundle/AppBundle/Batch/Batch.php
- src/Enhavo/Bundle/AppBundle/Batch/BatchManager.php
- src/Enhavo/Bundle/AppBundle/Batch/BatchTypeInterface.php
- src/Enhavo/Bundle/AppBundle/Batch/Type/AssignBatchType.php
- src/Enhavo/Bundle/AppBundle/Batch/Type/BaseBatchType.php
- src/Enhavo/Bundle/AppBundle/Batch/Type/DeleteBatchType.php
- src/Enhavo/Bundle/AppBundle/Batch/Type/FormBatchType.php
- src/Enhavo/Bundle/AppBundle/Controller/ResourceController.php
- src/Enhavo/Bundle/ContentBundle/Batch/PublishBatchType.php
- src/Enhavo/Bundle/NewsletterBundle/Batch/SendBatchType.php
- src/Enhavo/Bundle/NewsletterBundle/Batch/SendTestBatchType.php
Allow batch types to return the Response
> Allow batch types to return the Response

- src/Enhavo/Bundle/FormBundle/Twig/FormExtension.php
* Add `form_attr` for twig to render form attr individual
> Form attributes

- .scrutinizer.yml
> Fix scrutinizer test

- assets/node_modules/@enhavo/app/action/factory/FormActionFactory.ts
- assets/node_modules/@enhavo/app/action/model/DownloadAction.ts
- assets/node_modules/@enhavo/app/action/model/FormAction.ts
- assets/node_modules/@enhavo/app/modal/components/AjaxFormModalComponent.vue
- assets/node_modules/@enhavo/app/modal/model/AjaxFormModal.ts
- assets/node_modules/@enhavo/app/services/enhavo/action.yaml
- assets/node_modules/@enhavo/app/util/AxiosResponseHandler.ts
- config/routes/admin/person.yaml
- config/routes/admin/term.yaml
- src/App/Controller/PersonController.php
- src/App/Form/Type/PersonExportType.php
- src/Enhavo/Bundle/AppBundle/Action/Type/FormActionType.php
- src/Enhavo/Bundle/AppBundle/Filter/Type/BetweenFilterType.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/action.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/views/admin/resource/order/order.html.twig
* Add form action
* Add axios response helper
* Use arraybuffer for ajax modal to allow download
* Fix shop wording
> add form action

- assets/node_modules/@enhavo/app/assets/styles/components/_view-table.scss
- assets/node_modules/@enhavo/app/grid/Grid.ts
- assets/node_modules/@enhavo/app/grid/GridConfiguration.ts
- assets/node_modules/@enhavo/app/grid/column/components/Row.vue
- config/routes/admin/person.yaml
- src/Enhavo/Bundle/AppBundle/Action/Type/FormActionType.php
- src/Enhavo/Bundle/AppBundle/View/Type/IndexViewType.php
- src/Enhavo/Bundle/AppBundle/View/ViewUtil.php
- src/Enhavo/Bundle/MediaBundle/Factory/FileFactory.php
- src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yaml
* Add clickable flag for grid rows
* Fix creating temp file
> Add clickable flag

- src/Enhavo/Bundle/BlockBundle/Block/Type/VideoBlockType.php
- src/Enhavo/Bundle/BlockBundle/Resources/views/theme/block/video.html.twig
- src/Enhavo/Bundle/ContentBundle/Video/YoutubeProvider.php
* Fix missing youtube urls from https://gist.github.com/rodrigoborgesdeoliveira/987683cfbfcc8d800192da1e73adc486
* Prevent error if url is incorrect
> Change youtube regex

- src/Enhavo/Bundle/UserBundle/EventListener/SaveUserSubscriber.php
- src/Enhavo/Bundle/UserBundle/Model/User.php
- src/Enhavo/Bundle/UserBundle/Tests/EventListener/SaveUserSubscriberTest.php
- src/Enhavo/Bundle/UserBundle/Tests/User/UserManagerTest.php
- src/Enhavo/Bundle/UserBundle/User/UserManager.php
* use only on `update` funtion for `UserManger`
* remove old serialize function from fos user
> Cleanup user entity

- assets/node_modules/@enhavo/dependency-injection/compiler/Compiler.js
- assets/node_modules/@enhavo/dependency-injection/container/Argument.js
* Allow bool values in javascript dependency injection
> Allow bool values in di

- docs/source/guides/migration/index.rst
- docs/source/guides/migration/migrate-to-0.12.rst
- src/Enhavo/Bundle/UserBundle/EventListener/VerificationRequiredListenerSubscriber.php
- src/Enhavo/Bundle/UserBundle/Resources/translations/EnhavoUserBundle.de.yaml
- src/Enhavo/Bundle/UserBundle/composer.json
* Fix user verification message
* Add migration docs
> Fix user verification and docs

- assets/node_modules/@enhavo/vue-form/components/FormRowComponent.vue
- assets/node_modules/@enhavo/vue-form/index.ts
* Allow multiple form rendering
* Fix import form widget
> Allow multiple form rendering

- .github/mergify.yml
> Add backport rule

- assets/node_modules/@enhavo/dependency-injection/README.md
- assets/node_modules/@enhavo/dependency-injection/bin/dependency-injection.js
- assets/node_modules/@enhavo/dependency-injection/compiler/Compiler.js
- assets/node_modules/@enhavo/dependency-injection/container/Container.js
- assets/node_modules/@enhavo/dependency-injection/container/ContainerBuilder.js
- assets/node_modules/@enhavo/dependency-injection/container/Definition.js
- assets/node_modules/@enhavo/dependency-injection/loader/Loader.js
- assets/node_modules/@enhavo/dependency-injection/package.json
* Fix `di` command
* Add `factory` and `factoryMethod` options for di definitions
> Fix di factory command and add factory option

- assets/node_modules/@enhavo/app/compiler-pass/vue-components.js
- assets/node_modules/@enhavo/dependency-injection/bin/dependency-injection.js
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/HiddenVueType.php
* Fix vue-component compiler pass read only first dir
* Fix inspect don't show compiler changes
* Fix vue forms hidden field
> Fix di and vue hidden

- assets/node_modules/@enhavo/vue-form/data/FormData.ts
- assets/node_modules/@enhavo/vue-form/form/Form.ts
- assets/node_modules/@enhavo/vue-form/form/Theme.ts
- docs/source/book/vue-form-bundle/how-it-works.rst
- docs/source/guides/index.rst
- docs/source/guides/vue-form/how-to-customize-form.rst
- docs/source/guides/vue-form/index.rst
* Add `How to customize form` article
* Use visitor pattern to change form data
* Allow to use `parent` and `get()` for form data
> Add vue form visitors for theme

- src/Enhavo/Bundle/UserBundle/Security/Authentication/FormLoginAuthenticator.php
| Doc PR?       |  no
| Backport      | 0.11, 0.10
* Fix login failure path
> Fix login failure path

- assets/node_modules/@enhavo/app/compiler-pass/registry.js
- assets/node_modules/@enhavo/app/services/theme/services.yaml
- assets/node_modules/@enhavo/app/services/vue-form.yaml
- assets/node_modules/@enhavo/form/components/FormListComponent.vue
- assets/node_modules/@enhavo/form/components/FormListItemComponent.vue
- assets/node_modules/@enhavo/vue-form/form/Form.ts
- assets/node_modules/@enhavo/vue-form/form/FormFactory.ts
- assets/node_modules/@enhavo/vue-form/form/FormFactoryInterface.ts
- assets/node_modules/@enhavo/vue-form/form/FormVisitor.ts
- assets/node_modules/@enhavo/vue-form/form/Theme.ts
- assets/theme/base/components/FormCustomList.vue
- assets/theme/base/container.di.yaml
- assets/theme/base/controllers/VueFormController.ts
- docs/source/book/user-bundle/configuration.rst
- docs/source/book/vue-form-bundle/how-it-works.rst
- docs/source/book/vue-form-bundle/index.rst
- docs/source/book/vue-form-bundle/visitors.rst
- docs/source/guides/vue-form/how-to-customize-form.rst
- docs/source/reference/index.rst
- docs/source/reference/vue-form/form-list.rst
- docs/source/reference/vue-form/index.rst
- src/App/Controller/FormController.php
- src/Enhavo/Bundle/FormBundle/Form/VueType/ListVueType.php
- templates/theme/form/base.html.twig
* Use slots for form list
* Use `FormFactory` to  create forms
* Allow general form visitors
* Use theme only for a visitor collection
> Vue form list

- assets/node_modules/@enhavo/form/components/FormListComponent.vue
- assets/node_modules/@enhavo/form/components/FormListItemComponent.vue
- assets/node_modules/@enhavo/form/package.json
- assets/node_modules/@enhavo/vue-form/components/FormWidgetComponent.vue
- assets/theme/base/controllers/VueFormController.ts
- src/App/Controller/FormController.php
- src/Enhavo/Bundle/FormBundle/Form/Type/ListType.php
- src/Enhavo/Bundle/FormBundle/Form/VueType/ListVueType.php
- templates/theme/form/base.html.twig
* Add drag and drop for form-list
* Fix form widget compound rendering
> Add drag and drop for form-list

- assets/node_modules/@enhavo/form/components/FormListComponent.vue
- assets/node_modules/@enhavo/form/form/data/FormListData.ts
- assets/node_modules/@enhavo/vue-form/data/FormData.ts
- assets/theme/base/controllers/VueFormController.ts
- docs/source/book/vue-form-bundle/how-it-works.rst
- src/Enhavo/Bundle/VueFormBundle/Form/Extension/VueTypeExtension.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/ComponentVueType.php
- src/Enhavo/Bundle/VueFormBundle/Resources/config/services.yaml
* Add form-list onMove hook
* Add `component_visitor` option, to easy apply visitors on form types
* Update docs
> Add form-list onMove hook and component visitor option

- src/Enhavo/Bundle/ContentBundle/Video/VimeoProvider.php
Fixed PHP syntax error on versions 7.3 and lower
> [ContentBundle] Fixed PHP syntax error on versions 7.3 and lower

- src/Enhavo/Bundle/ShopBundle/Manager/ProductManager.php
> optimise product manager function; normalise function names

- docs/source/book/vue-form-bundle/visitors.rst
- src/Enhavo/Bundle/UserBundle/Configuration/Login/LoginConfiguration.php
- src/Enhavo/Bundle/UserBundle/Controller/SecurityController.php
- src/Enhavo/Bundle/UserBundle/DependencyInjection/Configuration.php
- src/Enhavo/Bundle/UserBundle/Event/UserEvent.php
- src/Enhavo/Bundle/UserBundle/EventListener/TooManyLoginAttemptsSubscriber.php
- src/Enhavo/Bundle/UserBundle/Form/EventListener/CredentialsEventSubscriber.php
- src/Enhavo/Bundle/UserBundle/Model/Credentials.php
- src/Enhavo/Bundle/UserBundle/Resources/config/services/controller.yaml
- src/Enhavo/Bundle/UserBundle/Resources/views/admin/security/login/login.html.twig
- src/Enhavo/Bundle/UserBundle/Security/Authentication/FormLoginAuthenticator.php
- src/Enhavo/Bundle/UserBundle/Tests/Security/Authentication/FormLoginAuthenticatorTest.php
* Fix vue form visitors doc
* Add repository method option for login
* Fire always a login failure event, but without user if it's not possible to resolve
* Save login form data into session
> Fix login and add repository method option

- src/Enhavo/Bundle/ShopBundle/Entity/Product.php
- src/Enhavo/Bundle/ShopBundle/Model/ProductAccessTrait.php
- src/Enhavo/Bundle/ShopBundle/Model/ProductInterface.php
- src/Enhavo/Bundle/ShopBundle/Repository/ProductOptionValueRepository.php
- src/Enhavo/Bundle/ShopBundle/Repository/ProductVariantRepository.php
- src/Enhavo/Bundle/ShopBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/config/doctrine/Product.orm.xml
- src/Enhavo/Bundle/ShopBundle/Resources/config/doctrine/ProductVariant.orm.xml
- src/Enhavo/Bundle/TaxonomyBundle/Entity/Term.php
- src/Enhavo/Bundle/TaxonomyBundle/EventListener/TermSubscriber.php
- src/Enhavo/Bundle/TaxonomyBundle/Model/TermInterface.php
- src/Enhavo/Bundle/TaxonomyBundle/Resources/config/doctrine/Term.orm.xml
- src/Enhavo/Bundle/TaxonomyBundle/Resources/config/services.yaml
- src/Enhavo/Bundle/TaxonomyBundle/Taxonomy/TaxonomyManager.php
- src/Enhavo/Bundle/TaxonomyBundle/composer.json
- src/Enhavo/Bundle/UserBundle/Model/User.php
- src/Enhavo/Bundle/UserBundle/Resources/config/validation.yaml
* Return always a default variant
* Add missing persits
* Replace gedmo slugable
* User enabled by default
> Fix shop and taxonomy

- assets/node_modules/@enhavo/app/action/model/FormAction.ts
- assets/node_modules/@enhavo/app/modal/model/AjaxFormModal.ts
- docs/source/book/vue-form-bundle/visitors.rst
- src/Enhavo/Bundle/AppBundle/Action/Type/FormActionType.php
- src/Enhavo/Bundle/UserBundle/Model/User.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/PasswordVueType.php
- src/Enhavo/Bundle/VueFormBundle/Resources/config/services.yaml
* Allow to reload window after form action
* Fix password type for vue
* Add visitor component doc
> Allow to reload window after form action

- src/Enhavo/Bundle/SearchBundle/DependencyInjection/Compiler/SearchEngineCompilerPass.php
- src/Enhavo/Bundle/ShopBundle/DependencyInjection/EnhavoShopExtension.php
- src/Enhavo/Bundle/ShopBundle/Entity/Order.php
- src/Enhavo/Bundle/ShopBundle/Entity/OrderItem.php
- src/Enhavo/Bundle/ShopBundle/EventListener/ProductVariantProxyReplaceSubscriber.php
- src/Enhavo/Bundle/ShopBundle/Model/AdjustmentInterface.php
- src/Enhavo/Bundle/ShopBundle/OrderProcessing/OrderPromotionProcessor.php
- src/Enhavo/Bundle/ShopBundle/Resources/config/services/order-processing.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/config/services/order.yaml
- src/Enhavo/Bundle/ShopBundle/Search/Filter/ProductVariantAttributesDataProvider.php
- src/Enhavo/Bundle/ShopBundle/Search/Filter/ProductVariantCategoriesDataProvider.php
- src/Enhavo/Bundle/ShopBundle/Search/Filter/ProductVariantEnabledDataProvider.php
- src/Enhavo/Bundle/ShopBundle/Search/Filter/ProductVariantPropertyDataProvider.php
- src/Enhavo/Bundle/ShopBundle/Shipping/DelegatingCalculator.php
- src/Enhavo/Bundle/ShopBundle/Shipping/DelegatingCalculatorInterface.php
- src/Enhavo/Bundle/ShopBundle/Taxation/Applicator/OrderItemsTaxesApplicator.php
- src/Enhavo/Bundle/ShopBundle/Taxation/Applicator/OrderShipmentTaxesApplicator.php
* Change order processing order
* Make `EngineInterface` accessable for autowireing
* Calculate order item and shipping tax on current price (may change during promotion)
* Allow indexing for product properties
> Fix order processing

- .github/workflows/subtree.yml
> Fix pushing 0.11 branch to subtrees

- src/Enhavo/Bundle/ShopBundle/Resources/config/doctrine/Product.orm.xml
- src/Enhavo/Bundle/ShopBundle/Resources/config/doctrine/ProductVariant.orm.xml
* Fix product picture cascades. They should remove if media file was deleted
> Fix product picture cascades

- src/Enhavo/Bundle/ShopBundle/EventListener/ProductVariantProxyReplaceSubscriber.php
* Fix proxy replace. In same cases the `uow` don't have computed all changes for insert entites on preFlush yet. That will happen after the hook and so we might have unreplaced proxies on flush, which will trigger an error. So we look up in our persits hook if we are inside a flush a keep the entity original until post flush replace it with our proxy again.
> Fix proxy replace

- src/Enhavo/Bundle/ShopBundle/Controller/OrderController.php
- src/Enhavo/Bundle/ShopBundle/Entity/Order.php
- src/Enhavo/Bundle/ShopBundle/Form/Type/OrderPromotionCouponType.php
- src/Enhavo/Bundle/ShopBundle/Form/Type/Promotion/NthOrderConfigurationType.php
- src/Enhavo/Bundle/ShopBundle/Model/OrderInterface.php
- src/Enhavo/Bundle/ShopBundle/Promotion/Checker/Rule/NthOrderRuleChecker.php
- src/Enhavo/Bundle/ShopBundle/Repository/OrderRepository.php
- src/Enhavo/Bundle/ShopBundle/Resources/config/services/promotion.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/translations/EnhavoShopBundle.de.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/translations/EnhavoShopBundle.en.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/views/admin/resource/order/order.html.twig
- src/Enhavo/Bundle/ShopBundle/Resources/views/theme/component/shop/cart-summary.html.twig
* Add nth rule checker for promotion
* change `getDiscountTotal` to `getDiscountedTotal`
* Add voucher info at order
> Add nth rule checker for promotion

- src/Enhavo/Bundle/BlockBundle/Maker/BlockDefinition.php
- src/Enhavo/Bundle/BlockBundle/Maker/Generator/DoctrineOrmField.php
- src/Enhavo/Bundle/BlockBundle/Maker/Generator/PhpClass.php
- src/Enhavo/Bundle/BlockBundle/Maker/Generator/PhpClassProperty.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/entity.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/item-entity.tpl.php
add traits option
add no orm possibility
fixed default remover typo
> [BlockBundle] Enhance block maker

- assets/node_modules/@enhavo/form/components/FormListComponent.vue
- assets/node_modules/@enhavo/form/form/helper/FormListHelper.ts
- assets/node_modules/@enhavo/form/form/model/FormList.ts
- assets/node_modules/@enhavo/form/helper/FormListHelper.ts
- src/Enhavo/Bundle/VueFormBundle/Form/Extension/VueTypeExtension.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/ComponentVueType.php
* Encapsulate form logic to helper for FormList
* Add `vue_data` form var to all form types, to easily pass data in `buildView`
* Allow `onCreate`callback in FormList
> Form list helper

- assets/node_modules/@enhavo/app/action/factory/DeleteActionFactory.ts
- assets/node_modules/@enhavo/app/action/factory/DuplicateActionFactory.ts
- assets/node_modules/@enhavo/app/action/model/DeleteAction.ts
- src/Enhavo/Bundle/AppBundle/Action/Type/DeleteActionType.php
DeleteAction did not make use of given message options in the Frontend.
> [AppBundle] DeleteAction fixes

- assets/node_modules/@enhavo/vue-form/components/FormCheckboxComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormRadioComponent.vue
- assets/node_modules/@enhavo/vue-form/model/CheckboxForm.ts
- assets/node_modules/@enhavo/vue-form/model/RadioForm.ts
- src/App/Controller/FormController.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/CheckboxVueType.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/RadioVueType.php
* Fix checkbox and radio vue form
> Fix checkbox and radio vue form

- assets/node_modules/@enhavo/app/compiler-pass/form-model-register.js
- assets/node_modules/@enhavo/app/services/vue-form.yaml
- assets/node_modules/@enhavo/form/services/components.yaml
- assets/node_modules/@enhavo/vue-form/form/FormFactory.ts
- assets/node_modules/@enhavo/vue-form/model/Form.ts
- assets/node_modules/@enhavo/vue-form/tests/form/FormFactory.mocha.ts
- assets/theme/base/container.di.yaml
- src/Enhavo/Bundle/FormBundle/Form/VueType/ListVueType.php
- src/Enhavo/Bundle/FormBundle/Form/VueType/WysiwygVueType.php
- src/Enhavo/Bundle/MediaBundle/Form/VueType/MediaVueType.php
- src/Enhavo/Bundle/VueFormBundle/Form/Extension/VueTypeExtension.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/CheckboxVueType.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/FormVueType.php
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/RadioVueType.php
* Add component model property. This is necessary because in the most cases you change the want to the component, you don't want to change the model. So we use a new property `componentModel` to control which model will be created
> feat: component model

- assets/node_modules/@enhavo/form/form/model/FormList.ts
- assets/node_modules/@enhavo/vue-form/form/FormEventDispatcher.ts
- assets/node_modules/@enhavo/vue-form/form/FormEventDispatcherInterface.ts
* form list dispatch also change event
* `on` alias for event dispatcher `addListener`
> feat: form list dispatch change, on alias for event dispatcher

- assets/node_modules/@enhavo/media/components/FormMediaComponent.vue
- assets/node_modules/@enhavo/media/form/model/MediaForm.ts
- assets/node_modules/@enhavo/vue-form/form/FormEventDispatcher.ts
- assets/node_modules/@enhavo/vue-form/form/FormEventDispatcherInterface.ts
- assets/node_modules/@enhavo/vue-form/form/FormVisitor.ts
- assets/node_modules/@enhavo/vue-form/tests/form/FormEventDispatcher.mocha.ts
| Tickets       | no
* fix media form events
* add `AbstractFormVisitor`
> fix: trigger correct media events

- src/Enhavo/Bundle/RoutingBundle/Twig/SlugifyExtension.php
Fixed twig filter slugify in RoutingBundle
> [RoutingBundle] Fixed twig filter slugify

- assets/node_modules/@enhavo/media/components/FormMediaItemComponent.vue
- assets/node_modules/@enhavo/media/form/MediaUtil.ts
- assets/node_modules/@enhavo/media/form/model/MediaForm.ts
- assets/node_modules/@enhavo/media/form/model/MediaItemForm.ts
- assets/node_modules/@enhavo/media/model/File.ts
- assets/node_modules/@enhavo/media/model/PrivateFile.ts
- assets/node_modules/@enhavo/media/resolver/FileResolver.ts
- assets/node_modules/@enhavo/media/resolver/FileUrlResolverInterface.ts
- assets/node_modules/@enhavo/media/services/components.yaml
- src/Enhavo/Bundle/FormBundle/Form/Type/ListType.php
- src/Enhavo/Bundle/MediaBundle/Form/Type/FileType.php
- src/Enhavo/Bundle/MediaBundle/Resources/config/serialization.yaml
- src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yaml
- src/Enhavo/Bundle/VueFormBundle/Form/VueType/FormVueType.php
* Show uploaded file in vue media form
> chore: show file in vue media form

- src/Enhavo/Bundle/MediaBundle/Form/Type/FileType.php
* use correct media entry type on transforming
* fix set media item component in configuration
> fix: use correct media entry type on transforming

- src/Enhavo/Bundle/SearchBundle/Filter/FilterData.php
- src/Enhavo/Bundle/ShopBundle/Entity/Product.php
- src/Enhavo/Bundle/ShopBundle/Entity/UserAddress.php
- src/Enhavo/Bundle/ShopBundle/Model/ProductAccessTrait.php
- src/Enhavo/Bundle/ShopBundle/Search/Filter/ProductVariantPropertyDataProvider.php
- src/Enhavo/Bundle/UserBundle/Controller/ResetPasswordController.php
- src/Enhavo/Bundle/UserBundle/Form/Data/ResetPassword.php
- src/Enhavo/Bundle/UserBundle/Form/Type/ResetPasswordRequestType.php
- src/Enhavo/Bundle/UserBundle/Repository/UserRepository.php
- src/Enhavo/Bundle/UserBundle/Resources/config/doctrine/User.orm.xml
- src/Enhavo/Bundle/UserBundle/Resources/config/validation.yaml
* Email und username is not unique anymore. 
* Fix initialize values
* Use identifier for reset password
* Fix product indexing
* Fix no default variant
> fix: user identifier and shop indexing bugs

- src/Enhavo/Bundle/UserBundle/User/UserManager.php
> fix: set password request date

- assets/node_modules/@enhavo/media/image-cropper/ImageCropperApp.ts
- assets/node_modules/@enhavo/media/image-cropper/components/ImageCropperStageComponent.vue
- assets/node_modules/@enhavo/media/services/enhavo/services.yaml
- src/Enhavo/Bundle/MediaBundle/Resources/translations/javascript.de.yaml
- src/Enhavo/Bundle/MediaBundle/Resources/translations/javascript.en.yaml
Fixed Imagecropper detection of unsaved changes
> [MediaBundle] Fixed Imagecropper detection of unsaved changes

- src/Enhavo/Bundle/AppBundle/Command/EmailSendCommand.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/command.yaml
Added simple command "enhavo:email:send" to debug email dispatch
> [AppBundle] Added command to send email

- assets/node_modules/@enhavo/app/action/model/FormAction.ts
- assets/node_modules/@enhavo/app/modal/model/AjaxFormModal.ts
- assets/node_modules/@enhavo/shop/action/model/CreateAttributeAction.ts
* fix: get form data from modal
> fix: get form data from modal

- src/Enhavo/Bundle/MediaBundle/Command/CollectGarbageCommand.php
- src/Enhavo/Bundle/MediaBundle/EventListener/GarbageCollectionSubscriber.php
> [AppBundle] Fixed batch delete

- src/Enhavo/Bundle/UserBundle/Resources/config/routes/admin/group.yaml
> [UserBundle] Fixed UserGroup delete

- src/Enhavo/Bundle/AppBundle/Resources/views/admin/view/base.html.twig
Fixed javascript error on login screen because of missing routes data by providing default empty routes data if not available
> [AppBundle] Fixed javascript error on login screen

- src/Enhavo/Bundle/SearchBundle/Command/IndexCommand.php
- src/Enhavo/Bundle/SearchBundle/DependencyInjection/Configuration.php
- src/Enhavo/Bundle/SearchBundle/DependencyInjection/EnhavoSearchExtension.php
- src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticSearchDocumentIdGenerator.php
- src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticSearchEngine.php
- src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticSearchIndexRemover.php
- src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticaORMAdapter.php
- src/Enhavo/Bundle/SearchBundle/Resources/config/services/elastic_search.yaml
Error tolerance for orphaned index entries
> [SearchBundle] Error tolerance for orphaned index entries

- src/Enhavo/Bundle/ShopBundle/Controller/PromotionCouponController.php
- src/Enhavo/Bundle/ShopBundle/Entity/Order.php
- src/Enhavo/Bundle/ShopBundle/Model/OrderInterface.php
- src/Enhavo/Bundle/ShopBundle/OrderProcessing/OrderPromotionCouponProcessor.php
- src/Enhavo/Bundle/ShopBundle/OrderProcessing/OrderPromotionProcessor.php
- src/Enhavo/Bundle/ShopBundle/Resources/config/services/order-processing.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/config/validation.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/translations/messages.de.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/translations/messages.en.yaml
* remove promotion coupon automatically if not eligible
* fix promotion rule typos
> feat: remove promotion coupon automatically if not eligible

- src/Enhavo/Bundle/CommentBundle/Resources/config/doctrine/Comment.orm.xml
This is a manual backport of pull request #1783.
> [CommentBundle] Removed cascade remove from comment to thread (Backport 0.12)

- src/Enhavo/Bundle/MediaBundle/Controller/FileController.php
| Backport      | 0.11, 0.12
Prevent http caching for StreamedResponse
> [MediaBundle] Prevent http caching for StreamedResponse

- assets/node_modules/@enhavo/app/vue/VueRegistry.ts
- assets/node_modules/@enhavo/form/form/model/ListForm.ts
- assets/node_modules/@enhavo/vue-form/components/FormLabelComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormRowComponent.vue
- assets/node_modules/@enhavo/vue-form/components/FormWidgetComponent.vue
- docs/source/book/vue-form-bundle/listener.rst
* Fix update names in ListType for vues
* Update listener docs
* Fix vue warning for overwriting components
> fix: list vue type, listener docs and overwrite components

- assets/node_modules/@enhavo/media/form/model/MediaForm.ts
- assets/theme/base/controllers/VueFormController.ts
- src/Enhavo/Bundle/MediaBundle/Form/Extension/FileVueTypeExtension.php
- src/Enhavo/Bundle/MediaBundle/Form/Extension/MediaExtension.php
- src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yaml
* fix media upload for images
* fix upload bar shown on every media type on page
> fix: media upload

- src/Enhavo/Bundle/FormBundle/Form/Type/ConditionalType.php
- src/Enhavo/Bundle/FormBundle/Tests/Form/Type/ConditionalTypeTest.php
* switch type with conditional form type
> fix: switch type with conditional form type

- src/Enhavo/Bundle/MultiTenancyBundle/Resources/config/services/menu.yaml
| Backport      | 0.10, 0.11, 0.12
* Fix `MultiTenancyController` for tenant switch
> fix: tenant switch

- src/Enhavo/Bundle/UserBundle/Configuration/FirewallConfigKeyProvider.php
- src/Enhavo/Bundle/UserBundle/DependencyInjection/Configuration.php
- src/Enhavo/Bundle/UserBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/UserBundle/Tests/DependencyInjection/ConfigurationTest.php
* allow multiple firewalls for user configuration
> feat: allow multiple firewalls for user configuration

- src/App/Controller/FormController.php
- src/Enhavo/Bundle/VueFormBundle/Form/Extension/ChoiceVueTypeExtension.php
- src/Enhavo/Bundle/VueFormBundle/Tests/Form/Extension/ChoiceVueTypeExtensionTest.php
* fix wrong value for vue choice type with expanded option
> fix: value for vue choice expanded

- assets/node_modules/@enhavo/vue-form/model/ChoiceForm.ts
fix choice with radio button, they didn't get unselected if you select another choice option, because the dom changed event is not triggered for unselected radio inputs
> fix: choice checked

- src/Enhavo/Bundle/MultiTenancyBundle/EventListener/TenantDoctrineFilterListener.php
fix throwing error if resolver can't resolve a tenant
> fix: resolve no tenant

- assets/node_modules/@enhavo/app/compiler-pass/vue-components.js
* Add chunkName option for vue compiler, to optimize chunks
> chore: add chunkName option for vue compiler

- src/Enhavo/Bundle/MediaBundle/Form/Type/MediaType.php
Set error bubbling to false for MediaType
> [MediaBundle] Set error bubbling to false for MediaType

- assets/node_modules/@enhavo/app/action/model/OpenAction.ts
- docs/source/reference/action/open-action.rst
- src/Enhavo/Bundle/AppBundle/Action/Type/OpenActionType.php
- src/Enhavo/Bundle/AppBundle/Resources/translations/EnhavoAppBundle.de.yml
- src/Enhavo/Bundle/AppBundle/Resources/translations/EnhavoAppBundle.en.yml
Option confirm for open action
> [AppBundle] Option confirm for open action

- src/Enhavo/Bundle/ArticleBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/CalendarBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/CommentBundle/Comment/AdminConfirmUrlGenerator.php
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/PageBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/PageBundle/Resources/config/app/translation.yaml
- src/Enhavo/Bundle/RoutingBundle/Resources/config/services/router.yaml
- src/Enhavo/Bundle/RoutingBundle/Router/Strategy/AdminStrategy.php
- src/Enhavo/Bundle/RoutingBundle/Twig/RouterExtension.php
- src/Enhavo/Bundle/ShopBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/TemplateBundle/Resources/config/app/config.yaml
Added strategy type 'admin' to generate complete direct links to admin update view of given resource
> [RoutingBundle] Added strategy type 'admin'

- assets/node_modules/@enhavo/app/assets/styles/components/_menu.scss
> fix: menu labels

- config/routes/dev/template.yaml
- config/routes/template/app.yaml
- data/hello.yaml
- data/hello2.php
- src/Enhavo/Bundle/AppBundle/Endpoint/TemplateEndpointType.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/services.yaml
* Add template endpoint, to help frontend devs testing templates
> feat: add template endpoint

- src/App/Endpoint/Extension/HelloEndpointExtension.php
- src/Enhavo/Bundle/ApiBundle/Endpoint/AbstractEndpointTypeExtension.php
- src/Enhavo/Bundle/ApiBundle/Endpoint/Endpoint.php
- src/Enhavo/Bundle/ApiBundle/Endpoint/EndpointTypeExtensionInterface.php
- src/Enhavo/Bundle/ApiBundle/EnhavoApiBundle.php
- src/Enhavo/Component/Type/TypeExtensionCompilerPass.php
Allow type extensions for endpoints
> feat: add endpoint type extension

- src/Enhavo/Bundle/AppBundle/Command/DebugEndpointTemplate.php
- src/Enhavo/Bundle/AppBundle/Endpoint/TemplateEndpointCollector.php
- src/Enhavo/Bundle/AppBundle/Endpoint/TemplateEndpointEntry.php
- src/Enhavo/Bundle/AppBundle/Endpoint/TemplateEndpointFilter.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Type/TemplateEndpointType.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/services.yaml
* add `debug:endpoint:template` command to get an overview of all template endpoints
* fix TemplateEndpoint loader
> feat: add debug:endpoint:template command

- config/services.yaml
- src/Enhavo/Bundle/ApiBundle/Endpoint/AbstractEndpointType.php
- src/Enhavo/Bundle/ApiBundle/Endpoint/AbstractEndpointTypeExtension.php
- src/Enhavo/Bundle/ApiBundle/Endpoint/Context.php
- src/Enhavo/Bundle/ApiBundle/Endpoint/Endpoint.php
- src/Enhavo/Bundle/ApiBundle/Endpoint/EndpointTrait.php
- src/Enhavo/Bundle/ApiBundle/Endpoint/Header.php
- src/Enhavo/Bundle/ApiBundle/Endpoint/Type/ApiEndpointType.php
- src/Enhavo/Bundle/ApiBundle/Tests/Endpoint/ContextTest.php
- src/Enhavo/Bundle/ApiBundle/Tests/Endpoint/EndpointTest.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Type/ViewEndpointType.php
- src/Enhavo/Component/Type/AbstractContainerType.php
* Add `EndpointTrait` which subscribe several services like in controllers
* Add response method to context
> feat: add endpoint trait with pre defined services

- src/Enhavo/Bundle/ApiBundle/Endpoint/Context.php
- src/Enhavo/Bundle/AppBundle/EnhavoAppBundle.php
* Fix compiler pass loading order
* Fix initialize header
> fix: compiler pass

- src/Enhavo/Bundle/AppBundle/Endpoint/Type/AreaEndpointType.php
- src/Enhavo/Bundle/AppBundle/Normalizer/FormDataNormalizer.php
- src/Enhavo/Bundle/AppBundle/Resources/config/serialization/routing.yaml
- src/Enhavo/Bundle/AppBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/AppBundle/Routing/ExposeRouteCollector.php
- src/Enhavo/Bundle/AppBundle/Routing/RouteCollectorInterface.php
- src/Enhavo/Bundle/AppBundle/Tests/Mock/RouterMock.php
- src/Enhavo/Bundle/MediaBundle/Resources/config/routes/theme/file.yaml
> feat: expose routes for endpoints

- src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/routes/admin/file.yaml
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/routes/admin/tag.yaml
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/routes/admin/newsletter.yaml
- src/Enhavo/Bundle/PaymentBundle/Resources/config/routes/admin/payment_method.yaml
- src/Enhavo/Bundle/RoutingBundle/Entity/Route.php
- src/Enhavo/Bundle/ShopBundle/Resources/config/routes/admin/product_attribute.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/config/routes/admin/promotion.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/config/routes/admin/promotion_coupon.yaml
- src/Enhavo/Bundle/ShopBundle/Resources/config/routes/theme/checkout.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/admin/change-password.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/user/change-email.yaml
* Fix controller actions in routes
* Fix creating route in form
> fix: routing

- config/packages/app.yaml
- src/Enhavo/Bundle/AppBundle/DependencyInjection/Compiler/RouteCollectorCompilerPass.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Extension/RouterEndpointExtensionType.php
- src/Enhavo/Bundle/AppBundle/EnhavoAppBundle.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/AppBundle/Routing/ChainRouteCollector.php
- src/Enhavo/Bundle/AppBundle/Routing/ExposeRouteCollector.php
- src/Enhavo/Bundle/AppBundle/Routing/RouteCollectorInterface.php
- src/Enhavo/Bundle/AppBundle/Twig/TwigRouter.php
- src/Enhavo/Bundle/PageBundle/Repository/PageRepository.php
- src/Enhavo/Bundle/PageBundle/Resources/config/services.yaml
- src/Enhavo/Bundle/PageBundle/Routing/PageCodeRouteCollector.php
- src/Enhavo/Bundle/PageBundle/Twig/PagePathExtension.php
- templates/theme/base.html.twig
* Add route collector chain and register collector by tags
* Use `page_code` with twig router
* Add `page_code_exists`
* Fix route collection in template endpoints
> feat: use page_path with normalized data

- assets/node_modules/@enhavo/app/controllers/FormController.ts
- assets/node_modules/@enhavo/app/services/vue-form.yaml
- assets/node_modules/@enhavo/app/vue/VueRegistry.ts
- src/App/Controller/FormController.php
- src/Enhavo/Bundle/AppBundle/Twig/RouterExtension.php
- src/Enhavo/Bundle/AppBundle/Twig/TwigRouter.php
- src/Enhavo/Bundle/PageBundle/Endpoint/PageEndpointType.php
- templates/theme/form/controller.html.twig
* Add stimulus form controller to deal with vue forms
* Add `RouterInterface` to `TwigRouter`
* Fix `router_generate` funtion in twig
> feat: add stimulus form controller

- .github/workflows/subtree.yml
Add subtree push for version 0.13
> chore: add subtree push for version 0.13

- src/Enhavo/Bundle/FormBundle/Controller/AutoCompleteController.php
- src/Enhavo/Bundle/FormBundle/Resources/config/services/controller.yaml
> fix: autocomplete controller

- src/Enhavo/Bundle/ContentBundle/Normalizer/ContentDataNormalizer.php
- src/Enhavo/Bundle/TaxonomyBundle/Resources/config/serialization.yaml
> fix: normalize data for blocks

- src/Enhavo/Bundle/AppBundle/Resources/config/services/twig.yaml
- src/Enhavo/Bundle/AppBundle/Resources/config/services/view.yaml
- src/Enhavo/Bundle/AppBundle/Twig/TwigExtension.php
- src/Enhavo/Bundle/AppBundle/View/Type/AppViewType.php
- src/Enhavo/Bundle/MediaBundle/DependencyInjection/Configuration.php
- src/Enhavo/Bundle/MediaBundle/Form/Type/FileType.php
- src/Enhavo/Bundle/MediaBundle/Resources/config/routes/theme/file.yaml
- src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yaml
- src/Enhavo/Bundle/MediaBundle/Tests/Form/Extension/MediaVueTypeExtensionTest.php
- src/Enhavo/Bundle/MediaBundle/Twig/MediaTwigExtension.php
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/views/admin/resource/file/main.html.twig
- src/Enhavo/Bundle/TaxonomyBundle/Resources/config/serialization.yaml
* Fix media parameters form
* Fix admin url routes
* Fix taxonomy normalize groups
> fix: media parameters and admin media_url

- assets/node_modules/@enhavo/app/encore/AppThemePackage.js
- assets/node_modules/@enhavo/app/routing/Router.ts
- assets/node_modules/@enhavo/app/services/routing.yaml
- assets/node_modules/@enhavo/app/services/theme/services.yaml
* Add js router for endpoint routing, this router will replace the core router, because the structure of passing the routes to the frontend was changed.
* [BC] Move images to assets folder
> feat: add js router for endpoint routing

- src/Enhavo/Bundle/AppBundle/Endpoint/Type/ViewEndpointType.php
- src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yaml
> fix: media template routes

- src/Enhavo/Bundle/ApiBundle/Data/Data.php
- src/Enhavo/Bundle/ApiBundle/Normalizer/AbstractDataNormalizer.php
- src/Enhavo/Bundle/ApiBundle/Normalizer/DataNormalizer.php
- src/Enhavo/Bundle/ApiBundle/Normalizer/DataNormalizerInterface.php
- src/Enhavo/Bundle/AppBundle/DependencyInjection/EnhavoAppExtension.php
- src/Enhavo/Bundle/AppBundle/Normalizer/RouteCollectionDataNormalizer.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/action.yaml
- src/Enhavo/Bundle/AppBundle/Resources/config/services/column.yaml
- src/Enhavo/Bundle/AppBundle/Resources/config/services/command.yaml
- src/Enhavo/Bundle/AppBundle/Resources/config/services/endpoint.yaml
- src/Enhavo/Bundle/AppBundle/Resources/config/services/filter.yaml
- src/Enhavo/Bundle/AppBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/BlockBundle/Normalizer/NodeDataNormalizer.php
* feat: prevent pre serialization if group is null
* chore: move endpoint services into extra file
> feat: prevent pre serialization if group is null

- assets/theme/routes.json
- config/routes.yaml
- src/Enhavo/Bundle/AppBundle/Endpoint/Type/AreaEndpointType.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/AppBundle/Routing/Loader/VueRouterLoader.php
* Add a vue router loader, that can read a json and add the routes to symfony
> feat: vue router loader

- src/Enhavo/Bundle/ArticleBundle/Resources/config/serialization.yaml
Serialization groups for Article
> [AppBundle] Serialization groups for Article

- config/routes.yaml
- src/Enhavo/Bundle/AppBundle/DependencyInjection/Compiler/TemplateExpressionLanguageCompilerPass.php
- src/Enhavo/Bundle/AppBundle/DependencyInjection/Configuration.php
- src/Enhavo/Bundle/AppBundle/DependencyInjection/EnhavoAppExtension.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Template/ExpressionLanguage/RefFunctionProvider.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Template/ExpressionLanguage/TemplateExpressionLanguageEvaluator.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Template/ExpressionLanguage/UrlFunctionProvider.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Template/Loader.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Type/TemplateEndpointType.php
- src/Enhavo/Bundle/AppBundle/EnhavoAppBundle.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/endpoint.yaml
- src/Enhavo/Bundle/AppBundle/Tests/Endpoint/Template/LoaderTest.php
- src/Enhavo/Bundle/MediaBundle/Endpoint/Extension/MediaRoutesEndpointExtensionType.php
- src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yaml
* Add new functions to template expression language: `ref`, `url`
* Add loader caching
* Evaluate data also in template data option
* Fix adding media routing in template endpoint
* Rename `media_routes` option to `media_routes_enabled` (BC)
> feat: improve template expression language

- data/hello_variant_1.yaml
- data/hello_variant_2.yaml
- data/routes/app.yaml
- src/Enhavo/Bundle/ApiBundle/Profiler/EndpointDataCollector.php
- src/Enhavo/Bundle/ApiBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/AppBundle/Command/DebugEndpointTemplate.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Template/TemplateEndpointCollector.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Template/TemplateEndpointEntry.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Type/TemplateEndpointType.php
- src/Enhavo/Bundle/AppBundle/Profiler/TemplateEndpointDataCollector.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/AppBundle/Resources/views/profiler/template_endpoint.html.twig
- templates/theme/endpoint/hello.html.twig
* Add variants option to template endpoint, to be able to load different data on the same route
* Add profiling infos to template variants
> feat: add template variants

- assets/node_modules/@enhavo/app/routing/Router.ts
> fix: check for variables in js router

- assets/node_modules/@enhavo/dependency-injection/package.json
- data/hello.yaml
- data/hello2.php
- data/routes/app.yaml
- src/Enhavo/Bundle/ApiBundle/Endpoint/Endpoint.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Template/ExpressionLanguage/LoadFunctionProvider.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Template/ExpressionLanguage/LoremIpsumFunctionProvider.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Template/ExpressionLanguage/LoremIpsumGenerator.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Template/Loader.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Type/TemplateEndpointType.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/endpoint.yaml
* Fix missing lodash package in dependency injection
* Rename template expr funtion `include` to `load`
* `load` can handle multiple files
* `lorem_ipsum` has parameters to adjust the output
> feat: improve lorem ipsum and rename include to load

- src/Enhavo/Bundle/AppBundle/Endpoint/Type/AreaEndpointType.php
- src/Enhavo/Bundle/ArticleBundle/Controller/ArticleController.php
- src/Enhavo/Bundle/ArticleBundle/Resources/config/routes/api/article.yaml
- src/Enhavo/Bundle/PageBundle/Controller/PageController.php
- src/Enhavo/Bundle/PageBundle/Resources/config/routes/api/page.yaml
* Expose api routes to group `api`
* Fix area template routes group
> fix: api routes

- assets/node_modules/@enhavo/vue-form/model/Form.ts
* Add `remove` and `add` function to vue form model
> feat: add and remove child in vue form

- src/Enhavo/Bundle/UserBundle/Resources/config/app/config.yaml
* Fix admin login route config
> fix: admin login

- src/Enhavo/Bundle/RoutingBundle/Entity/Route.php
- src/Enhavo/Bundle/RoutingBundle/Form/Type/RouteType.php
- src/Enhavo/Bundle/RoutingBundle/Manager/RouteManager.php
- src/Enhavo/Bundle/TranslationBundle/Translator/Route/RouteTranslator.php
> fix: route name generation

- assets/node_modules/@enhavo/user/assets/styles/login.scss
Fixed error causing enhavo iframe views to not be scrollable
> [UserBundle] Fixed error causing enhavo iframe views to not be scrollable

- src/Enhavo/Component/CleverReach/composer.json
| Backport     | 0.13, 0.12, 0.11
Fixed composer autoload setting for CleverReach Component
> [Component CleverReach] Fixed composer autoload setting

- src/Enhavo/Bundle/AppBundle/Endpoint/Extension/RouterEndpointExtensionType.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Type/TemplateEndpointType.php
- src/Enhavo/Bundle/AppBundle/Profiler/TemplateEndpointDataCollector.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/endpoint.yaml
- src/Enhavo/Bundle/AppBundle/Routing/ExposeRouteCollector.php
- src/Enhavo/Bundle/AppBundle/Routing/RouteCollectorTrait.php
- src/Enhavo/Bundle/PageBundle/Routing/PageCodeRouteCollector.php
* Fix twig routes in template type
* Add status code to template type
> fix: twig routing

- src/Enhavo/Bundle/ContentBundle/Resources/config/app/search.yaml
- src/Enhavo/Bundle/RoutingBundle/Resources/config/services/router.yaml
- src/Enhavo/Bundle/SearchBundle/Command/InitCommand.php
- src/Enhavo/Bundle/SearchBundle/Command/SearchSuggestCommand.php
- src/Enhavo/Bundle/SearchBundle/Engine/DatabaseSearch/DatabaseSearchEngine.php
- src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticSearchEngine.php
- src/Enhavo/Bundle/SearchBundle/Engine/Filter/Filter.php
- src/Enhavo/Bundle/SearchBundle/Engine/Result/EntitySubjectLoader.php
- src/Enhavo/Bundle/SearchBundle/Engine/Result/ResultEntry.php
- src/Enhavo/Bundle/SearchBundle/Engine/Result/ResultSummary.php
- src/Enhavo/Bundle/SearchBundle/Engine/Result/SubjectLoaderInterface.php
- src/Enhavo/Bundle/SearchBundle/Engine/SearchEngineInterface.php
- src/Enhavo/Bundle/SearchBundle/Filter/FilterData.php
- src/Enhavo/Bundle/SearchBundle/Filter/Type/PropertyFilterType.php
- src/Enhavo/Bundle/SearchBundle/Index/Type/HtmlIndexType.php
- src/Enhavo/Bundle/SearchBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/SearchBundle/Result/ResultConverter.php
* [BC] A search result is now a summary that contains entries to add more meta data
* Add suggest function to elastic search engine
* Add fuzzy search
* Fix filter types
> feat: meta data for search results

- src/Enhavo/Bundle/AppBundle/Area/AreaResolverInterface.php
- src/Enhavo/Bundle/AppBundle/Area/ChainAreaResolver.php
- src/Enhavo/Bundle/AppBundle/Area/FirewallAreaResolver.php
- src/Enhavo/Bundle/AppBundle/Area/PathAreaResolver.php
- src/Enhavo/Bundle/AppBundle/Area/RequestAreaResolver.php
- src/Enhavo/Bundle/AppBundle/DependencyInjection/Configuration.php
- src/Enhavo/Bundle/AppBundle/DependencyInjection/EnhavoAppExtension.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Extension/VueRouteEndpointExtensionType.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Type/AreaEndpointType.php
- src/Enhavo/Bundle/AppBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/AppBundle/Resources/config/services/area.yaml
- src/Enhavo/Bundle/AppBundle/Resources/config/services/endpoint.yaml
- src/Enhavo/Bundle/AppBundle/Tests/DependencyInjection/ConfigurationTest.php
- src/Enhavo/Bundle/ArticleBundle/Controller/ArticleController.php
- src/Enhavo/Bundle/ArticleBundle/Resources/config/routes/api/article.yaml
- src/Enhavo/Bundle/ArticleBundle/Resources/config/routes/theme/article.yaml
- src/Enhavo/Bundle/NavigationBundle/Endpoint/NavigationEndpointExtension.php
- src/Enhavo/Bundle/PageBundle/Controller/PageController.php
- src/Enhavo/Bundle/PageBundle/ErrorRenderer/SpecialPageErrorRenderer.php
- src/Enhavo/Bundle/PageBundle/Resources/config/routes/api/page.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/admin/api/login.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/admin/api/reset-password.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/admin/login.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/admin/reset-password.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/api/login.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/api/reset-password.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/user/login.yaml
* introduce high level area concept
* all endpoint options of an area are configurable over the configuration
> feat: area options

- src/Enhavo/Bundle/UserBundle/Controller/UserController.php
- src/Enhavo/Bundle/UserBundle/DependencyInjection/Configuration.php
- src/Enhavo/Bundle/UserBundle/DependencyInjection/EnhavoUserExtension.php
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/admin/change-password.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/services/view.yaml
- src/Enhavo/Bundle/UserBundle/View/Type/ChangePasswordViewType.php
| Backport     | 0.13, 0.12, 0.11
Fix for wrong target resource in change password action
> [UserBundle] Fix for wrong target resource in change password action

- src/Enhavo/Bundle/FormBundle/Tests/Form/Type/ConditionalTypeTest.php
* Add submit test for conditional type
> chore: add submit test for conditional type

- assets/node_modules/@enhavo/api/.github/workflows/release.yml
- assets/node_modules/@enhavo/api/package.json
> chore: fix ci for api assets

- docs/book/general/template-mode.md
- docs/book/index.md
- docs/book/search-bundle/search.md
- docs/reference/index.md
- docs/reference/template-expression/index.md
- docs/reference/template-expression/load.md
- docs/reference/template-expression/lorem_ipsum.md
- docs/reference/template-expression/ref.md
- docs/reference/template-expression/url.md
* docs for template mode and template expressions
> docs: template mode

- assets/node_modules/@enhavo/app/components/preview/ApplicationComponent.vue
Fixed Javascript error in preview
> [AppBundle] Fixed Javascript error in preview

- composer.json
- src/Enhavo/Bundle/AppBundle/Maker/Analyze/ConstructArgument.php
- src/Enhavo/Bundle/AppBundle/Maker/Analyze/ConstructArgumentFinder.php
- src/Enhavo/Bundle/AppBundle/Maker/Analyze/TestClassAnalyzer.php
- src/Enhavo/Bundle/AppBundle/Maker/Analyze/UseItem.php
- src/Enhavo/Bundle/AppBundle/Maker/Analyze/UseItemFinder.php
- src/Enhavo/Bundle/AppBundle/Maker/MakeTest.php
- src/Enhavo/Bundle/AppBundle/Maker/Test/InsideBundleTestClassResolver.php
- src/Enhavo/Bundle/AppBundle/Maker/Test/TestClassResolverInterface.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/maker.yaml
- src/Enhavo/Bundle/AppBundle/Resources/skeleton/Test.tpl.php
- src/Enhavo/Bundle/AppBundle/composer.json
Add test maker to create phpunit test with a dependency structure template.
> feat: add test maker

- docs/book/general/template-mode.md
* docs: add expose route section to template mode
* docs: add dependency restriction section to template mode
> docs: expose route

- assets/node_modules/@enhavo/form/form/model/WysiwygForm.ts
Fix import statement for tinymce in wysiwy vue form
> fix: tinymce in wysiwyg form

- docs/book/general/working-with-vue.md
- docs/book/index.md
Add new doc file "Working with vue"
> docs: working with vue

- src/Enhavo/Bundle/MediaBundle/Controller/FileController.php
- src/Enhavo/Bundle/MediaBundle/Http/FileRangeResponse.php
- src/Enhavo/Bundle/MediaBundle/Http/FileResponse.php
> cherry pick FileRangeResponse update

- docs/book/bundles/api-bundle/api-documentation.md
- docs/book/bundles/api-bundle/endpoint-extensions.md
- docs/book/bundles/api-bundle/endpoints.md
- docs/book/bundles/api-bundle/index.md
- docs/book/bundles/api-bundle/installation.md
- docs/book/bundles/api-bundle/introduction.md
- docs/book/bundles/api-bundle/normalization.md
- docs/book/bundles/search-bundle/installation.md
- docs/book/general/area.md
- docs/guides/migration/migrate-to-0.14.md
* docs: add api bundle content for endpoints
> docs: add api bundle content for endpoints

- src/Enhavo/Bundle/SearchBundle/Engine/DatabaseSearch/DatabaseSearchEngine.php
- src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticSearchEngine.php
- src/Enhavo/Bundle/SearchBundle/Engine/SearchEngineInterface.php
- src/Enhavo/Bundle/SearchBundle/Repository/IndexRepository.php
Added function count to SearchEngineInterface; Implemented function count for DatabaseSearchEngine
> [SearchBundle] Added function count to SearchEngineInterface (Backport 0.13)

- composer.json
- src/Enhavo/Bundle/CalendarBundle/composer.json
- src/Enhavo/Bundle/MediaBundle/Factory/FileFactory.php
- src/Enhavo/Bundle/MediaBundle/Tests/Factory/FileFactoryTest.php
- src/Enhavo/Bundle/MediaBundle/composer.json
- src/Enhavo/Bundle/NewsletterBundle/composer.json
- src/Enhavo/Component/CleverReach/composer.json
| Backport     | 0.14 0.13 
Remove guzzle-http from composer.json.
> Remove guzzle-http from composer.json.

- docs/book/bundles/user-bundle/configuration.md
- docs/book/bundles/user-bundle/installation.md
- docs/book/general/area.md
- docs/guides/migration/migrate-to-0.14.md
> docs: update user docs

- migrations/Version20240626134008.php
- src/Enhavo/Bundle/RoutingBundle/Resources/config/doctrine-route/Symfony.Component.Routing.Route.orm.xml
* fix: missing route condition in orm
> fix: missing route condition in orm

- src/Enhavo/Bundle/RoutingBundle/Resources/config/doctrine-route/Symfony.Component.Routing.Route.orm.xml
> fix: condition column

- src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticSearchEngine.php
- src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticaORMAdapter.php
[SearchBundle] Proper pagination for elastic search
> [SearchBundle] Proper pagination for elastic search

- src/Enhavo/Bundle/ApiBundle/Profiler/JsonDumper.php
- src/Enhavo/Bundle/ApiBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/ApiBundle/Resources/views/profiler/endpoint.html.twig
- src/Enhavo/Bundle/ApiBundle/Twig/ApiProfilerExtension.php
| BC-Break?    | yes/no
Add json dump tab to profiler
> feat: json dump

- src/Enhavo/Bundle/DoctrineExtensionBundle/EventListener/ReferenceSubscriber.php
- src/Enhavo/Bundle/DoctrineExtensionBundle/Tests/EventListener/ReferenceSubscriberTest.php
| Backport     | 0.13, 0.14
Fix deletions, where a doctrine reference class has a referenece and this class will be removed. It was not removed, because the reference listener just see it is not tracked by the unit of work and try to persist it again. Now, we check if it is not marked for deletetion as well.
> fix: doctrine reference deletions

- src/App/Endpoint/SettingEndpoint.php
- src/Enhavo/Bundle/SettingBundle/Endpoint/Extension/SettingEndpointExtensionType.php
- src/Enhavo/Bundle/SettingBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/SettingBundle/Setting/AbstractSettingType.php
- src/Enhavo/Bundle/SettingBundle/Setting/Setting.php
- src/Enhavo/Bundle/SettingBundle/Setting/SettingManager.php
- src/Enhavo/Bundle/SettingBundle/Setting/SettingTypeInterface.php
- src/Enhavo/Bundle/SettingBundle/Setting/Type/BaseSettingType.php
The extension provides a flexible way to add settings either by specifying groups or by including all settings.
> Setting groups

- src/Enhavo/Bundle/ShopBundle/Model/ProductAccessTrait.php
| Backport     | 0.12, 0.13, 0.14
Fixed bug in ProductAccessTrait removePicture
> [ShopBundle] Fixed bug in ProductAccessTrait removePicture

- src/Enhavo/Bundle/AppBundle/Mailer/MailerManager.php
- src/Enhavo/Bundle/AppBundle/Mailer/Message.php
Add possibility to send to address array.
> Add possibility to send to address array.

- assets/node_modules/@enhavo/form/type/ListItem.ts
- assets/node_modules/@enhavo/form/type/ListType.ts
- config/packages/enhavo_app.yaml
- config/packages/sylius_resources.yaml
- config/routes/admin/table.yaml
- src/App/Entity/Table.php
- src/App/Entity/TableCell.php
- src/App/Entity/TableRow.php
- src/App/Form/Type/TableCellType.php
- src/App/Form/Type/TableRowType.php
- src/App/Form/Type/TableType.php
| Tickets      | Fix #2097
Do only change the value of the first [data-position] to prevent updates on subordinary [data-position].
On remove item splice only one item in order to prevent ListType of loosing track of items.
> [FormBundle] ListType Sort Feature Fix

- src/Enhavo/Bundle/SearchBundle/Command/MetadataCommand.php
- src/Enhavo/Bundle/SearchBundle/Resources/config/services/services.yaml
> Add command to check the metadata in enhavo_search.yaml.

- src/Enhavo/Bundle/AppBundle/Resources/skeleton/routing.tpl.php
> Fix routing generation.

- .github/workflows/ci.yml
- composer.json
- config/packages/test/services.yaml
- package.json
- src/App/Entity/Person.php
- src/Enhavo/Bundle/AppBundle/Tests/Action/Type/CloseActionTypeTest.php
- src/Enhavo/Bundle/AppBundle/composer.json
- src/Enhavo/Bundle/ResourceBundle/Tests/Batch/Type/BaseBatchTypeTest.php
- src/Enhavo/Bundle/SearchBundle/Resources/config/services/services.yaml
> fix: ci testing and checks

- composer.json
- src/Enhavo/Bundle/AppBundle/composer.json
* fix symfony/filesystem version, so all symfony packages are same version
> fix: symfony/filesystem version

- assets/admin/vite.config.js
- assets/node_modules/@enhavo/form/package.json
- assets/theme/manifest.yml
- assets/theme/tsconfig.json
- docs/guides/migration/migrate-to-0.15.md
- src/App/Fixtures/AbstractFixture.php
- src/Enhavo/Bundle/AppBundle/Vite/ViteManager.php
- src/Enhavo/Bundle/ArticleBundle/Resources/config/services.yaml
- src/Enhavo/Bundle/BlockBundle/Resources/config/services/command.yaml
- src/Enhavo/Bundle/BlockBundle/Resources/config/services/factory.yaml
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/services/newsletter.yaml
- src/Enhavo/Bundle/PageBundle/Resources/config/resources/page.yaml
- src/Enhavo/Bundle/PageBundle/Resources/config/services.yaml
- src/Enhavo/Bundle/ResourceBundle/DependencyInjection/Compiler/ResourceCompilerPass.php
| Backport     | no
* fix: naming convention of factory services
* fix: missing auto wireing binds
* docs: udpate migration guide
> fix: services

- assets/admin/vite.config.js
- src/Enhavo/Bundle/AppBundle/Command/DebugEndpointTemplateCommand.php
- src/Enhavo/Bundle/AppBundle/Command/DebugTemplateCommand.php
- src/Enhavo/Bundle/AppBundle/Command/DebugVueRoutesCommand.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/command.yaml
- src/Enhavo/Bundle/AppBundle/Resources/views/admin/app/view.html.twig
- src/Enhavo/Bundle/AppBundle/Resources/views/admin/base.html.twig
- src/Enhavo/Bundle/AppBundle/Resources/views/admin/main/index.html.twig
- src/Enhavo/Bundle/AppBundle/Resources/views/admin/view/app.html.twig
- src/Enhavo/Bundle/AppBundle/Resources/views/admin/view/base.html.twig
- src/Enhavo/Bundle/AppBundle/Resources/views/theme/base-user.html.twig
- src/Enhavo/Bundle/AppBundle/Vue/RouteProvider/VueRouteProviderInterface.php
- src/Enhavo/Bundle/ContentBundle/Resources/views/theme/base.html.twig
- src/Enhavo/Bundle/PageBundle/Resources/config/resources/page.yaml
| Backport     | no
* feat: add `debug:vue-routes` command
* fix: vue routes optimization
* fix: favicon
* fix: page filters
> feat: add vue routes debug command

- docs/book/bundles/resource-bundle/resource.md
- docs/guides/migration/index.md
- docs/guides/migration/migrate-to-0.15.md
- src/Enhavo/Bundle/ResourceBundle/Doctrine/MetadataListener.php
- src/Enhavo/Bundle/ResourceBundle/Resources/config/services/services.yaml
| Backport     | no
* fix: overwrite doctrine repository class to make sure the same repository class is used system wide.
* docs: update migration guide
> fix: overwrite doctrine repository class

- assets/node_modules/@enhavo/app/assets/styles/components/flash-message.scss
- assets/node_modules/@enhavo/app/assets/styles/components/grid.scss
- assets/node_modules/@enhavo/app/components/filter/FilterBar.vue
- assets/node_modules/@enhavo/app/components/filter/FilterCheckbox.vue
- assets/node_modules/@enhavo/app/components/flash-message/FlashMessage.vue
- assets/node_modules/@enhavo/app/components/flash-message/FlashMessages.vue
- assets/node_modules/@enhavo/app/components/form/FormAdminRow.vue
- assets/node_modules/@enhavo/app/flash-message/FlashMessenger.ts
- assets/node_modules/@enhavo/app/vite/fantasticon-plugin/defaults.js
- assets/node_modules/@enhavo/form/assets/styles/module/_form.scss
- assets/node_modules/@enhavo/form/assets/styles/module/_list.scss
- assets/node_modules/@enhavo/form/assets/styles/module/_poly-collection.scss
- assets/node_modules/@enhavo/form/components/FormAutoComplete.vue
- assets/node_modules/@enhavo/form/components/FormList.vue
- assets/node_modules/@enhavo/form/components/FormListItem.vue
- assets/node_modules/@enhavo/form/components/FormPolyCollection.vue
- assets/node_modules/@enhavo/form/components/FormPolyCollectionItem.vue
- src/Enhavo/Bundle/AppBundle/Resources/translations/javascript.de.yml
- src/Enhavo/Bundle/AppBundle/Resources/translations/javascript.en.yml
fixed icon font display; flash message position change and added removability; styled filter bar; bugfix select2 in autocomplete multiple choice
> fixed styles and select2

- assets/node_modules/@enhavo/form/components/FormChoiceTree.vue
- assets/node_modules/@enhavo/form/components/FormChoiceTreeRow.vue
- assets/node_modules/@enhavo/form/form/model/ChoiceTreeForm.ts
- assets/node_modules/@enhavo/form/services/components.yaml
- assets/node_modules/@enhavo/form/services/form.yaml
- config/packages/app.yaml
- config/packages/enhavo_app.yaml
- config/resources/category.yaml
- config/resources/person.yaml
- config/routes/admin/category.yaml
- config/routes/admin_api/category.yaml
- migrations/Version20241202210036.php
- migrations/Version20241203204311.php
- src/App/Entity/Person.php
- src/App/Form/Type/PersonType.php
- src/Enhavo/Bundle/FormBundle/Form/Extension/EntityTreeTypeExtension.php
- src/Enhavo/Bundle/FormBundle/Form/Type/EntityTreeType.php
- src/Enhavo/Bundle/FormBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/TaxonomyBundle/Form/Type/TermType.php
- src/Enhavo/Bundle/TaxonomyBundle/Resources/config/resources/term.yaml
* fix: choice tree ui
* chore: add category for testing
* chore: use one menu for all test entities
> fix: choice tree

- assets/node_modules/@enhavo/media/assets/styles/_media.scss
- assets/node_modules/@enhavo/media/components/FormMedia.vue
- assets/node_modules/@enhavo/media/components/FormMediaItem.vue
- assets/node_modules/@enhavo/media/form/model/MediaForm.ts
- assets/node_modules/@enhavo/media/form/model/MediaItemForm.ts
- src/Enhavo/Bundle/BlockBundle/Form/Type/GalleryBlockType.php
[MediaBundle] Fix style for edit parameters section of MediaFormType
> [MediaBundle] Fix style for edit parameters section of MediaFormType

- assets/node_modules/@enhavo/app/assets/styles/core/form.scss
- assets/node_modules/@enhavo/app/assets/styles/import/blueprints.scss
- assets/node_modules/@enhavo/app/components/form/FormAdminRow.vue
- assets/node_modules/@enhavo/form/assets/styles/module/_form.scss
- assets/node_modules/@enhavo/form/assets/styles/module/_select2.scss
- assets/node_modules/@enhavo/form/components/FormAutoComplete.vue
- assets/node_modules/@enhavo/form/components/FormSelect2ChoiceCollapsed.vue
- assets/node_modules/@enhavo/media/assets/styles/_media.scss
- assets/node_modules/@enhavo/vue-form/components/FormErrorsComponent.vue
> various style fixes

- src/Enhavo/Bundle/BlockBundle/Duplicate/BlockNodeDuplicateType.php
- src/Enhavo/Bundle/BlockBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/MediaBundle/Duplicate/Type/FileDuplicateType.php
- src/Enhavo/Bundle/MediaBundle/Factory/FileFactory.php
- src/Enhavo/Bundle/ResourceBundle/Duplicate/DuplicateFactory.php
- src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/CollectionDuplicateType.php
- src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/CollectionReferenceDuplicateType.php
- src/Enhavo/Bundle/ResourceBundle/Resources/config/services/duplicate.yaml
- src/Enhavo/Bundle/RevisionBundle/DependencyInjection/Configuration.php
- src/Enhavo/Bundle/RevisionBundle/DependencyInjection/EnhavoRevisionExtension.php
- src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticSearchEngine.php
- src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticSearchIndexRemover.php
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/api/login.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/api/reset-password.yaml
* feat: add duplicate types
* fix: elastic dsn
* chore: remove restore config
> feat: add duplicate types

- assets/admin/tsconfig.json
- assets/theme/tsconfig.json
- src/Enhavo/Bundle/CommentBundle/Action/CommentsActionType.php
- src/Enhavo/Bundle/ResourceBundle/Collection/ListCollection.php
- src/Enhavo/Bundle/ResourceBundle/Collection/TableCollection.php
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/admin_api/user.yaml
* fix: user auto complete
* fix: table collection pagination
* fix: list collection criteria with expression
* fix: ts warnings
> fix: user auto complete, table collection pagination

- assets/node_modules/@enhavo/vue-form/model/Form.ts
- src/Enhavo/Bundle/ResourceBundle/Endpoint/Type/ResourceCreateEndpointType.php
- src/Enhavo/Bundle/ResourceBundle/Input/Input.php
- src/Enhavo/Bundle/ResourceBundle/Input/InputInterface.php
[VueFormBundle] Fixes for js Form.morphMerge()
[ResourceBundle] Allow to set resource
> Fixes for Form.morphMerge() and allow to add resource on input 

- assets/node_modules/@enhavo/form/components/FormICheckCheckbox.vue
- assets/node_modules/@enhavo/form/components/FormICheckRadio.vue
* fix: icheck checkbox for check and uncheck
> fix: icheck checkbox for check and uncheck 

- assets/node_modules/@enhavo/app/components/resource/ResourceIndex.vue
- assets/node_modules/@enhavo/app/expression-language/ExpressionLanguage.ts
- assets/node_modules/@enhavo/app/package.json
- assets/node_modules/@enhavo/app/services/admin/expression-language.yaml
- assets/node_modules/@enhavo/vue-form/model/Form.ts
- config/packages/enhavo_app.yaml
- package.json
- src/Enhavo/Bundle/ArticleBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/CommentBundle/Action/CommentsActionType.php
- src/Enhavo/Bundle/CommentBundle/Column/CommentSubjectLabelColumnType.php
- src/Enhavo/Bundle/CommentBundle/Column/CommentSubjectTitleColumnType.php
- src/Enhavo/Bundle/CommentBundle/DependencyInjection/Configuration.php
- src/Enhavo/Bundle/CommentBundle/DependencyInjection/EnhavoCommentExtension.php
- src/Enhavo/Bundle/CommentBundle/Entity/Comment.php
- src/Enhavo/Bundle/CommentBundle/Manager/CommentManager.php
- src/Enhavo/Bundle/CommentBundle/Menu/CommentMenuType.php
- src/Enhavo/Bundle/CommentBundle/Resources/config/resources/comment.yaml
- src/Enhavo/Bundle/CommentBundle/Resources/config/resources/thread.yaml
- src/Enhavo/Bundle/CommentBundle/Resources/config/resources/thread_comment.yaml
- src/Enhavo/Bundle/CommentBundle/Resources/config/routes/admin/comment.yaml
- src/Enhavo/Bundle/CommentBundle/Resources/config/routes/admin/thread_comment.yaml
- src/Enhavo/Bundle/CommentBundle/Resources/config/routes/admin_api/comment.yaml
- src/Enhavo/Bundle/CommentBundle/Resources/config/routes/admin_api/thread_comment.yaml
- src/Enhavo/Bundle/CommentBundle/Resources/config/services.yaml
- src/Enhavo/Bundle/PageBundle/Resources/config/services.yaml
- src/Enhavo/Bundle/ResourceBundle/Action/Type/SaveActionType.php
- src/Enhavo/Bundle/ResourceBundle/Endpoint/Type/ResourceCreateEndpointType.php
- src/Enhavo/Bundle/ResourceBundle/Resources/config/services/endpoint.yaml
| Feature?     | yes
* feat: add comment subject config to build all comment list
* fix: comments views and actions
* fix: create endpoint route parameters
* chore: remove expression language package and replace with eval
> fix: comments

- data/routes/_routes.yaml
- src/Enhavo/Bundle/MediaBundle/Endpoint/Type/TemplateFileEndpointType.php
- src/Enhavo/Bundle/MediaBundle/FileNotFound/CreateDummyFileNotFoundHandler.php
- src/Enhavo/Bundle/MediaBundle/Media/FormatManager.php
- src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yaml
[MediaBundle] Allow generating formats in template mode
> [MediaBundle] Allow generating formats in template mode

- src/Enhavo/Bundle/NavigationBundle/Form/Type/NodeCollectionType.php
[NavigationBundle] Fix for error in navigation form
> [NavigationBundle] Fix for error in navigation form

- src/Enhavo/Bundle/MediaBundle/Duplicate/Type/FileDuplicateType.php
- src/Enhavo/Bundle/PageBundle/Form/Type/PageType.php
- src/Enhavo/Bundle/PageBundle/Resources/config/doctrine/Page.orm.xml
- src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/DateTimeDuplicateType.php
- src/Enhavo/Bundle/ResourceBundle/Resources/config/services/duplicate.yaml
- src/Enhavo/Bundle/RevisionBundle/Batch/Type/BinDeleteBatchType.php
- src/Enhavo/Bundle/RevisionBundle/Resources/config/services/services.yaml
* fix: delete bin resources
* feat:  duplicate date type
> fix: delete bin

- assets/node_modules/@enhavo/media/action/MediaFormatAction.ts
- assets/node_modules/@enhavo/media/assets/styles/_media.scss
- assets/node_modules/@enhavo/media/components/ActionMediaFormat.vue
[MediaBundle] Style for Format-Action in MediaType
> [MediaBundle] Style for Format-Action in MediaType

- src/Enhavo/Bundle/NavigationBundle/NavItem/Type/NavItemType.php
- src/Enhavo/Bundle/NavigationBundle/Resources/config/services.yaml
[NavigationBundle] Enable translation for NavItem labels
> [NavigationBundle] Enable translation for NavItem labels

- assets/node_modules/@enhavo/app/components/resource/ResourceInput.vue
- assets/node_modules/@enhavo/app/tab/model/FormTab.ts
[AppBundle] Changes to FormTab
> [AppBundle] Changes to FormTab

- src/Enhavo/Bundle/CommentBundle/Action/CommentsActionType.php
> fix: comments action

- assets/node_modules/@enhavo/form/assets/styles/module/_poly-collection.scss
- assets/node_modules/@enhavo/form/components/FormPolyCollection.vue
- assets/node_modules/@enhavo/form/components/FormPolyCollectionAddButton.vue
- assets/node_modules/@enhavo/form/form/model/PolyCollectionForm.ts
- src/Enhavo/Bundle/FormBundle/Resources/translations/javascript.de.yaml
- src/Enhavo/Bundle/FormBundle/Resources/translations/javascript.en.yaml
[FormBundle] Form type PolyCollection: AddButton at more position, text filter for add button items
> [FormBundle] Form type PolyCollection: AddButton at more position, text filter for add button items

- assets/node_modules/@enhavo/app/manager/ResourcePreviewManager.ts
> fix: execute js in preview

- assets/admin/vite.config.js
- assets/node_modules/@enhavo/app/components/column/ColumnAction.vue
- assets/node_modules/@enhavo/form/assets/styles/module/_select2.scss
- assets/node_modules/@enhavo/form/components/FormAutoComplete.vue
- assets/theme/vite.config.js
- src/Enhavo/Bundle/AppBundle/Resources/config/services/action.yaml
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/resources/group.yaml
Fix for initial value in AutoCompleteEntityType with multiple false
Fix for missing CORS Header in vite dev
Fix configuration for Newsletter Group
> AutoCompleteEntityType Bugfix (and more)

- assets/node_modules/@enhavo/form/components/FormAutoComplete.vue
[FormBundle] Bugfix for AutoComplete Type
> [FormBundle] Bugfix for AutoComplete Type

- assets/node_modules/@enhavo/media/components/FormMedia.vue
- assets/node_modules/@enhavo/media/components/FormMediaItem.vue
[MediaBundle] Fix MediaType drag/drop sorting
> [MediaBundle] Fix MediaType drag/drop sorting

- assets/node_modules/@enhavo/vue-form/model/Form.ts
- src/Enhavo/Bundle/AppBundle/composer.json
- src/Enhavo/Bundle/MediaLibraryBundle/Action/MediaLibrarySelectActionType.php
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/services.yml
* fix: vue form remove on non existing childs
* fix: serializer dependencies
* fix: unused router in media lib select action
> fix: several small bugs

- src/Enhavo/Bundle/ResourceBundle/Duplicate/DuplicateFactory.php
- src/Enhavo/Bundle/ResourceBundle/Resources/config/services/duplicate.yaml
- src/Enhavo/Bundle/ResourceBundle/Tests/Duplicate/DuplicateFactoryTest.php
* fix: duplicate factory for extended entities
> fix: duplicate factory for extended entities

- src/Enhavo/Bundle/BlockBundle/DependencyInjection/CompilerPass/BlockManagerCompilerPass.php
* fix: block factory definitions
> fix: block factory definitions

- assets/node_modules/@enhavo/app/action/model/AutoSaveAction.ts
- assets/node_modules/@enhavo/app/action/model/SaveAction.ts
- assets/node_modules/@enhavo/app/manager/ResourceIndexManager.ts
- assets/node_modules/@enhavo/app/manager/ResourceInputManager.ts
- assets/node_modules/@enhavo/dependency-injection/container/ContainerBuilder.js
- assets/node_modules/@enhavo/media-library/manager/MediaLibraryManager.ts
- src/Enhavo/Bundle/AppBundle/Resources/translations/EnhavoAppBundle.en.yml
- src/Enhavo/Bundle/AppBundle/Resources/translations/javascript.en.yml
- src/Enhavo/Bundle/MediaBundle/Validator/Constraints/ClamAvValidator.php
- src/Enhavo/Bundle/NewsletterBundle/Resources/translations/EnhavoNewsletterBundle.en.yaml
* feat: use promise queue to sync save requests
* fix: occurred typo
> feat: use promise queue to sync save requests

- src/Enhavo/Bundle/ArticleBundle/Entity/Article.php
- src/Enhavo/Bundle/BlockBundle/Block/BlockManager.php
- src/Enhavo/Bundle/BlockBundle/Block/Cleaner.php
- src/Enhavo/Bundle/BlockBundle/Entity/Node.php
- src/Enhavo/Bundle/CalendarBundle/Entity/Appointment.php
- src/Enhavo/Bundle/NewsletterBundle/Entity/Newsletter.php
- src/Enhavo/Bundle/PageBundle/Entity/Page.php
- src/Enhavo/Bundle/PageBundle/Resources/config/resources/page.yaml
- src/Enhavo/Bundle/TemplateBundle/Entity/Template.php
* fix: block manager `findRootResource` for not associated resources
> fix: block node get root

- assets/node_modules/@enhavo/app/batch/model/UrlBatch.ts
- assets/node_modules/@enhavo/app/components/resource/ResourceIndex.vue
- src/Enhavo/Bundle/CalendarBundle/Resources/config/routes/admin_api/appointment.yaml
- src/Enhavo/Bundle/NavigationBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/NavigationBundle/Resources/config/routes/admin_api/navigation.yaml
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/routes/admin_api/group.yaml
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/routes/admin_api/newsletter.yaml
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/routes/admin_api/pending_subscriber.yaml
- src/Enhavo/Bundle/ResourceBundle/Batch/Type/BaseBatchType.php
- src/Enhavo/Bundle/ResourceBundle/Exception/MetadataException.php
- src/Enhavo/Bundle/ResourceBundle/ExpressionLanguage/PermissionExpressionFunctionProvider.php
- src/Enhavo/Bundle/SettingBundle/Resources/config/resources/setting.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/admin_api/group.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/admin_api/user.yaml
* fix: missing batch routes and detect missing route at url batch
> fix: batch routes

- data/content.html
- data/message.yaml
- data/routes/test/world.yaml
- data/template/message.html.twig
- docs/reference/template-expression/get_content.md
- docs/reference/template-expression/index.md
- docs/reference/template-expression/render.md
- src/Enhavo/Bundle/AppBundle/Endpoint/Template/ExpressionLanguage/GetContentFunctionProvider.php
- src/Enhavo/Bundle/AppBundle/Endpoint/Template/ExpressionLanguage/RenderFunctionProvider.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/endpoint.yaml
* feat: add function `render` and `get_content` to template expressions
> feat: add function render and get_content to template expressions

- assets/node_modules/@enhavo/form/components/wysiwyg/FormWysiwygTableInlineForm.vue
[FormBundle] Fix table translations
> [FormBundle] Fix table translations

- data/routes/test/world.yaml
- src/Enhavo/Bundle/AppBundle/Resources/config/services/endpoint.yaml
- src/Enhavo/Bundle/MultiTenancyBundle/ExpressionLanguage/TenantExpressionFunctionProvider.php
- src/Enhavo/Bundle/MultiTenancyBundle/Resources/config/services/general.yaml
- src/Enhavo/Bundle/ResourceBundle/ExpressionLanguage/PermissionExpressionFunctionProvider.php
- src/Enhavo/Bundle/ResourceBundle/ExpressionLanguage/RequestResourceExpressionVariableProvider.php
- src/Enhavo/Bundle/ResourceBundle/ExpressionLanguage/ResourceExpressionFunctionProviderInterface.php
- src/Enhavo/Bundle/ResourceBundle/ExpressionLanguage/ResourceExpressionLanguage.php
- src/Enhavo/Bundle/ResourceBundle/ExpressionLanguage/ResourceExpressionVariableProviderInterface.php
- src/Enhavo/Bundle/ResourceBundle/ExpressionLanguage/RouteResolverExpressionFunctionProvider.php
- src/Enhavo/Bundle/ResourceBundle/ExpressionLanguage/UserResourceExpressionVariableProvider.php
* chore: make resource expression interfaces compatible to symfony `ResourceExpressionFunctionProviderInterface`
* chore: simplfy resource expression variables interface
* fix: missing url expr tag
> chore: resource expression interface

- docs/book/bundles/resource-bundle/resource.md
- src/Enhavo/Bundle/MultiTenancyBundle/DependencyInjection/Compiler/ProviderCompilerPass.php
* fix: autowire multi tenancy provider
> Fix autowire multi tenancy provider

- src/Enhavo/Bundle/SearchBundle/Command/IndexCommand.php
- src/Enhavo/Bundle/SearchBundle/Engine/DatabaseSearch/DatabaseSearchEngine.php
- src/Enhavo/Bundle/SearchBundle/Engine/ElasticSearch/ElasticSearchEngine.php
- src/Enhavo/Bundle/SearchBundle/Engine/NullEngine.php
- src/Enhavo/Bundle/SearchBundle/Engine/SearchEngineInterface.php
* add arguments for search engine reindex
* improve reindex memory usage for elastic search
* improve reindex output for elastic search
> feat: add arguments for search engine reindex

- src/Enhavo/Bundle/ContentBundle/Resources/config/routes/theme/sitemap.yaml
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/translations/EnhavoMediaLibraryBundle.de.yaml
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/translations/EnhavoMediaLibraryBundle.en.yaml
- src/Enhavo/Bundle/UserBundle/Resources/config/routes/admin_api/user.yaml
- Fix sitemap endpoint configuration in ContentBundle
- Add roles for MediaItem in MediaLibraryBundle
- Fix user delete route in UserBundle
> [ContentBundle/UserBundle/MediaLibraryBundle] Fixes

- migrations/Version20250307042403.php
- src/App/Entity/Block/TestBlock.php
- src/Enhavo/Bundle/VueFormBundle/Form/Extension/ChoiceVueTypeExtension.php
* fix: choice type full name for multiple select
> fix: choice type full name for multiple select

- src/Enhavo/Bundle/MediaLibraryBundle/Form/Type/ItemType.php
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/resources/item.yaml
- src/Enhavo/Bundle/MediaLibraryBundle/Resources/config/services.yml
[MediaLibraryBundle] Add frontend url to Item form
> [MediaLibraryBundle] Add frontend url to Item form

- src/Enhavo/Bundle/MediaBundle/Routing/UrlGenerator.php
> fix: url generator for cli

- assets/node_modules/@enhavo/app/action/model/PreviewAction.ts
- assets/node_modules/@enhavo/app/client/AbortableErrorHandler.ts
- assets/node_modules/@enhavo/app/client/ClientInterface.ts
- assets/node_modules/@enhavo/app/client/NotFoundErrorHandler.ts
- assets/node_modules/@enhavo/app/collection/CollectionResourceItem.ts
- assets/node_modules/@enhavo/app/collection/model/ListCollection.ts
- assets/node_modules/@enhavo/app/collection/model/TableCollection.ts
- assets/node_modules/@enhavo/app/column/ColumnInterface.ts
- assets/node_modules/@enhavo/app/manager/ResourceIndexManager.ts
- assets/node_modules/@enhavo/app/manager/ResourceInputManager.ts
- assets/node_modules/@enhavo/app/manager/ResourcePreviewManager.ts
- assets/node_modules/@enhavo/app/services/admin/client.yaml
- assets/node_modules/@enhavo/app/services/admin/colllection.yaml
- assets/node_modules/@enhavo/app/services/admin/manager.yaml
- src/Enhavo/Bundle/AppBundle/EnhavoAppBundle.php
- src/Enhavo/Bundle/AppBundle/Resources/translations/javascript.de.yml
- src/Enhavo/Bundle/AppBundle/Resources/translations/javascript.en.yml
* fix update preview url after save
* add abort handler for abordable errors
* add 404 error handling for client
* handle errors in collection, input and preview
> feat: improve error messages

- docs/book/bundles/media-bundle/file-entity.md
- docs/book/bundles/media-bundle/form-type.md
- docs/book/bundles/media-bundle/format.md
- docs/book/bundles/media-bundle/index.md
- docs/book/bundles/resource-bundle/input.md
- docs/book/components/type/define-type.md
- docs/book/components/type/installation.md
* docs: add media form docs
* docs: improve component type
> docs: add media form docs

- assets/admin/vite.config.js
- assets/node_modules/@enhavo/app/vite/rollup-plugin-container-di.js
feat: add enable chunks option for di chunks
> feat: enable chunks option

- assets/node_modules/@enhavo/app/vite/rollup-plugin-container-di.js
* fix: enable chunking only in prod
> fix: enable chunking only in prod

- assets/node_modules/@enhavo/app/action/model/RevisionAwareRestoreAction.ts
- assets/node_modules/@enhavo/app/services/admin/action.yaml
- src/Enhavo/Bundle/RevisionBundle/Action/Type/RevisionAwareRestoreActionType.php
- src/Enhavo/Bundle/RevisionBundle/Endpoint/Type/RevisionAwareRestoreType.php
> fix: restore bin

- assets/node_modules/@enhavo/app/action/model/DropdownAction.ts
- assets/node_modules/@enhavo/app/action/model/PreviewWindowAction.ts
- assets/node_modules/@enhavo/app/components/action/ActionDropdown.vue
- assets/node_modules/@enhavo/app/index.ts
- assets/node_modules/@enhavo/app/services/admin/action.yaml
- src/Enhavo/Bundle/AppBundle/Action/Type/DropdownActionType.php
- src/Enhavo/Bundle/AppBundle/Action/Type/PreviewActionType.php
- src/Enhavo/Bundle/AppBundle/Action/Type/PreviewDropdownActionType.php
- src/Enhavo/Bundle/AppBundle/Action/Type/PreviewWindowActionType.php
- src/Enhavo/Bundle/AppBundle/Resources/config/services/action.yaml
- src/Enhavo/Bundle/AppBundle/Resources/translations/EnhavoAppBundle.de.yml
- src/Enhavo/Bundle/AppBundle/Resources/translations/EnhavoAppBundle.en.yml
- src/Enhavo/Bundle/ArticleBundle/Resources/config/resources/article.yaml
- src/Enhavo/Bundle/NewsletterBundle/Resources/config/resources/newsletter.yaml
- src/Enhavo/Bundle/PageBundle/Resources/config/resources/page.yaml
- src/Enhavo/Bundle/PageBundle/Resources/config/routes/admin_api/page.yaml
- src/Enhavo/Bundle/PageBundle/Resources/translations/EnhavoPageBundle.de.yaml
- src/Enhavo/Bundle/PageBundle/Resources/translations/EnhavoPageBundle.en.yaml
- src/Enhavo/Bundle/RoutingBundle/Action/Type/LinkActionType.php
- src/Enhavo/Bundle/RoutingBundle/Resources/config/services/general.yaml
- src/Enhavo/Bundle/RoutingBundle/Resources/translations/EnhavoRoutingBundle.de.yaml
- src/Enhavo/Bundle/RoutingBundle/Resources/translations/EnhavoRoutingBundle.en.yaml
* feat: add preview on new window action
* feat: add preview dropdrown action
* fix: dropdown action
* feat: add link action
* feat: add open page action
* feat: add `onPreviewRefresh` callback
> feat: add preview on new window and open page action

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/subtree.yml
> chore: fix removed ubuntu runner

- src/Enhavo/Bundle/FormBundle/Form/EventListener/MapSubmittedUuidDataListener.php
Detect missing or blank uuid fields on list und poly collection forms
> feat: show missing uuid error

- docs/book/bundles/resource-bundle/resource.md
- docs/reference/duplicate/clone.md
- docs/reference/duplicate/collection-reference.md
- docs/reference/duplicate/collection.md
- docs/reference/duplicate/datetime.md
- docs/reference/duplicate/file.md
- docs/reference/duplicate/index.md
- docs/reference/duplicate/inherit-options.md
- docs/reference/duplicate/model.md
- docs/reference/duplicate/property.md
- docs/reference/duplicate/reference.md
- docs/reference/duplicate/string.md
- docs/reference/index.md
- src/App/Entity/Person.php
- src/Enhavo/Bundle/ResourceBundle/Duplicate/Type/StringDuplicateType.php
- src/Enhavo/Bundle/ResourceBundle/Resources/config/services/duplicate.yaml
> docs: duplicate reference

- src/Enhavo/Bundle/MediaBundle/Resources/config/services/media.yaml
> fix: invalid http cache

- src/Enhavo/Bundle/RevisionBundle/DependencyInjection/Configuration.php
- src/Enhavo/Bundle/RevisionBundle/DependencyInjection/EnhavoRevisionExtension.php
- src/Enhavo/Bundle/RevisionBundle/Doctrine/RevisionFilter.php
- src/Enhavo/Bundle/RevisionBundle/EventListener/RevisionDoctrineFilterListener.php
- src/Enhavo/Bundle/RevisionBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/RevisionBundle/Resources/config/services/services.yaml
- src/Enhavo/Bundle/RevisionBundle/Tests/Doctrine/RevisionFilterTest.php
- src/Enhavo/Bundle/RevisionBundle/Tests/Mock/RevisionMock.php
Enhance RevisionFilter to take subclasses into account 
Introduce KernelListener to load RevisionFilter
Introduce doctrine_filter setting
> [RevisionBundle] Enhance RevisionFilter Mechanism

- assets/node_modules/@enhavo/app/controllers/FormController.ts
- assets/node_modules/@enhavo/form/services/admin/form.yaml
- assets/node_modules/@enhavo/form/services/admin/services.yaml
- assets/node_modules/@enhavo/form/services/form.yaml
- assets/theme/container.di.yaml
- assets/theme/entrypoints/main.js
- assets/theme/vite.config.js
- src/App/Controller/FormController.php
- src/App/Endpoint/Form/AbstractFormEndpointType.php
- src/App/Endpoint/Form/FormListEndpointType.php
- templates/theme/form/base.html.twig
- templates/theme/form/form.html.twig
* fix: form assets theme integration
> fix: form assets theme integration

- src/Enhavo/Bundle/BlockBundle/Maker/BlockDefinition.php
- src/Enhavo/Bundle/BlockBundle/Maker/Generator/DoctrineOrmField.php
- src/Enhavo/Bundle/BlockBundle/Maker/Generator/DoctrineOrmRelation.php
- src/Enhavo/Bundle/BlockBundle/Maker/Generator/DoctrineOrmYaml.php
- src/Enhavo/Bundle/BlockBundle/Maker/Generator/FormTypeField.php
- src/Enhavo/Bundle/BlockBundle/Maker/Generator/PhpClassProperty.php
- src/Enhavo/Bundle/BlockBundle/Maker/MakeBlock.php
- src/Enhavo/Bundle/BlockBundle/Resources/block/templates/BlockNodeType.yaml
- src/Enhavo/Bundle/BlockBundle/Resources/block/templates/BooleanType.yaml
- src/Enhavo/Bundle/BlockBundle/Resources/block/templates/DateTimeType.yaml
- src/Enhavo/Bundle/BlockBundle/Resources/block/templates/HeadlineType.yaml
- src/Enhavo/Bundle/BlockBundle/Resources/block/templates/ListType.yaml
- src/Enhavo/Bundle/BlockBundle/Resources/block/templates/MediaType.yaml
- src/Enhavo/Bundle/BlockBundle/Resources/block/templates/MediaTypeMultiple.yaml
- src/Enhavo/Bundle/BlockBundle/Resources/block/templates/PositionType.yaml
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/block-type.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/entity.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/factory.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/form-type.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/skeleton/block/item-entity.tpl.php
- src/Enhavo/Bundle/BlockBundle/Resources/views/maker/block/enhavo_config_entry.yml.twig
- src/Enhavo/Bundle/BlockBundle/Tests/Maker/Generator/PhpClassPropertyTest.php
- Remove BlockFactories
- Add property attributes option
- Slim down resulting code
- Enhance resulting code in terms of modern php versions
- Supplement built in block maker templates
> [BlockBundle] Block Maker Update

- src/Enhavo/Bundle/MediaBundle/Filter/Filter/VideoImageFilter.php
[MediaBundle] Fix VideoImageFilter ffmpeg error output same as input
> [MediaBundle] Fix VideoImageFilter ffmpeg error output same as input

- src/Enhavo/Bundle/FormBundle/DependencyInjection/Configuration.php
- src/Enhavo/Bundle/FormBundle/DependencyInjection/EnhavoFormExtension.php
- src/Enhavo/Bundle/FormBundle/Resources/config/services/twig.yaml
- src/Enhavo/Bundle/FormBundle/Tests/Twig/HtmlSanitizerTest.php
- src/Enhavo/Bundle/FormBundle/Twig/FormatExtension.php
[FormBundle] Allow global configuration of html_sanitize
> [FormBundle] Allow global configuration of html_sanitize

- src/Enhavo/Bundle/RedirectBundle/Resources/config/app/config.yaml
- src/Enhavo/Bundle/RedirectBundle/Resources/config/services.yaml
fix redirect controller service
> fix: redirect
